### ISSUE TITLE
`sendKeys` with `{reset: true}` blurring

### ISSUE THREAD

**Issue by joneshf** [n1k0/casperjs#1052]
It appears that if you have a call to `sendKeys` with an option of `{reset: true}`, then it will blur the element once the reset is done. If I'm following the logic correctly: [this call](https://github.com/n1k0/casperjs/blob/bc1a5ba6440c60081b2cf444030107c6801c0153/modules/casper.js#L1623) gets to [this line](https://github.com/n1k0/casperjs/blob/d68f88dc768fb82ea30d4c40c752cd6fd7f21989/modules/clientutils.js#L908) and causes the element to blur, [the next line](https://github.com/n1k0/casperjs/blob/bc1a5ba6440c60081b2cf444030107c6801c0153/modules/casper.js#L1625) tries to click the element again.

This causes an issue for me, as I have an `input` that I want to change the entire value of. When the input is blurred, it is removed from the DOM. So if `sendKeys` is blurring whenever the `input` is reset, I actually lose the input, and can't move on to the next line, as this throws an error.

Can `reset` be changed to not blur? These seem like they should be independent.

**Comment by erikmontes** [comment]
Use `keepFocus`:
```js
{reset: true, keepFocus: true}
```
http://casperjs.readthedocs.org/en/latest/modules/casper.html#options

**Comment by joneshf** [comment]
Sorry, I forgot about this issue. I'm also unsure what I did to fix it, but thanks for the `keepFocus` hint.
