### ISSUE TITLE
1.1-beta3 - cannot find module 'casper'

### ISSUE THREAD

**Issue by timscott** [n1k0/casperjs#1062]
Installed casperjs 1.1-beta3:

```> brew install capserjs --devel```

Then run:

```> capserjs test.coffee```

> test.coffee
```coffeescript
require('/path/to/test2.coffee').do_it()
``` 

> test2.coffee
```coffeescript
exports.do_it = ->
  casper = require('casper').create()
```

Get error:

```
Error: Cannot find module 'casper'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  /path/to/test2.coffee:5
  test.coffee:3
  test.coffee:5
```

I thought maybe I need to call ```patchRequire```, so I add this to the first line of ```test.coffee```

```coffeescript
require = patchRequire require
```

Then I get this error:

```
TypeError: 'undefined' is not an object (evaluating 'require.patched')

  /usr/local/Cellar/casperjs/1.1-beta3/libexec/bin/bootstrap.js:197 in patchRequire
  test.coffee:4
  test.coffee:8
```

Seems like some kind of bug or problem with installation.

**Comment by Skoks** [comment]
Same problem!

**Comment by ollehudga** [comment]
same problem

**Comment by brunoqueiros** [comment]
+ 1

**Comment by albertian** [comment]
same problem

**Comment by hyusetiawan** [comment]
same problem

**Comment by Palsskv** [comment]
same problem

**Comment by n1k0** [comment]
With coffeescript you need to refer the global scope using the `global` namespace:

```coffeescript
require = patchRequire global.require

exports.do_it = ->
  casper = require('casper').create()
```

I'll update the docs as this is far from obvious, admittedly.

**Comment by n1k0** [comment]
Bah, this was documented already, have a look at the warning section at the top of [this page](http://docs.casperjs.org/en/latest/writing_modules.html):

> When using CoffeeScript global.require must be passed to patchRequire() instead of just require.

**Comment by Gerst20051** [comment]
:+1:
