### ISSUE TITLE
Version is no longer 1.1.0-beta3

### ISSUE THREAD

**Issue by frankcarey** [n1k0/casperjs#1074]
I was trying to install the 1.1.0-dev version and when I was running `$ casperjs` I was still getting ` CasperJS version 1.1.0-beta3` , but after some more testing I realize this IS the dev version I am using, but the version seems to be pulling directly from package.json, so this is out of date and added to my confusion since the docs say that it should say something like `1.1.0-DEV`

**Comment by istr** [comment]
Integrated that hint into preparation branch for 1.1.0-beta4.
