### ISSUE TITLE
casperjs 1.1-beta executing asynchronously at CLI level

### ISSUE THREAD

**Issue by enzeart** [n1k0/casperjs#1112]
The CLI for casperjs is executing asynchronously from the command line. The command finishes executing before casperjs itself does any work. As a result, the command always has an exit code of 0 even when tests fail. This is causing issues with build tools that utilize casperjs. The error scenarios are as follows.

1. Build tool calls capserjs.
2. It complete successfully and immediately since execution of the tests are being delegated to another thread.
3. Build tool reports successful build.
4. Casperjs finally executes sometime later and reports a failed test.

It looks like 1.0.4 executes synchronously and might remedy the issue until it's addressed. Can you make 1.0.4 available via npm?

**Comment by paazmaya** [comment]
Can you share a minimal working example code in which this behaviour can be seen?

**Comment by enzeart** [comment]
After retesting it looks like this may have been an issue with the build tool itself. I may have mixed tests while I was dealing with the issue and attributed the behavior to the wrong component at the time. Sorry for the confusion and thanks for the reply. Closing this issue.
