### ISSUE TITLE
New 1.1-beta release?

### ISSUE THREAD

**Issue by paazmaya** [n1k0/casperjs#1117]
It would be great to have a named release, if that is still possible, to follow the `1.1` line.

It has been a while from `1.1-beta3` and while I have been using `master` as a direct replacement for it, there has not been any major issues, at least in my use cases...

**Comment by n1k0** [comment]
You're right… I'm overbusy with my new position as a full time Mozilla employee. But I'll try to release 1.1 stable in the next few weeks.

**Comment by paazmaya** [comment]
Great to hear (that I am right)!

@n1k0 please let me know if there is something I could do to help in getting it released...

**Comment by n1k0** [comment]
@paazmaya the first thing would be to triage issues/PR; most of them are invalid/obsolete/wontfix but there are certainly some worth addressing… and I lack time so much :/

If you want to help, you can start browsing old issues/PR and close them when appropriate (I can add you as a contributor so you can do so)

**Comment by lukeasrodgers** [comment]
@n1k0 I would be happy to help with this as well, if you want extra hands.

**Comment by paazmaya** [comment]
@n1k0 I could start putting labels for the issues, and could try to create a pull request which adds tests for those issues which have enough data...

**Comment by rdpanek** [comment]
@n1k0 I have now time for work on support PhantoJS2.0

**Comment by paazmaya** [comment]
Great @rdpanek !

**Comment by n1k0** [comment]
@paazmaya @rdpanek Thanks guys for the help :)

**Comment by paazmaya** [comment]
@n1k0 I could merge some of the most trivial PRs which are touching documentation, if I could have `contributor` status. Can I?

**Comment by n1k0** [comment]
@paazmaya Sure, you're now a collaborator. Handle with care ;)

**Comment by paazmaya** [comment]
@n1k0 Thank you for the trust.

**Comment by gamma** [comment]
I know you guys are busy preparing the next release ... any estimation on when you will be ready?

**Comment by paazmaya** [comment]
According to the milestone, https://github.com/n1k0/casperjs/milestones/1.1, there are still 15 issues open.
In addition to those, there are several issues and pull requests which are most likely to be included....

**Comment by amerikan** [comment]
Here's a new issue for `1.1-beta4` release: https://github.com/n1k0/casperjs/issues/1365

**Comment by istr** [comment]
Closing in favor of #1365.
