### ISSUE TITLE
Trigger: Ctrl + Left click

### ISSUE THREAD

**Issue by tsiknas** [n1k0/casperjs#1125]
Greetings,
I am trying to trigger a "Ctrl + Left click" at an element, which normally will open a popup window.
At this point, I am using the following method (from phantomjs):
casper.page.sendEvent('click', 100, 100, 'left', 0x04000000);
// and then
casper.echo(casper.popups.length);
// which returns 0

Can anybody confirm that clicking with a modifier is possible?

**Comment by rdpanek** [comment]
I don't know but, I think it can not work with bookmarks - right?

**Comment by cndev** [comment]
Sorry, but I can't follow your comment.

After some further testing, I actually managed to open a popup.
So, I can confirm that the above is possible.
