### ISSUE TITLE
Switch to ESLint from JSHint

### ISSUE THREAD

**Issue by paazmaya** [n1k0/casperjs#1133]
ESLint offers more rules and thus better control over the code syntax, validation, and linting.

http://eslint.org/docs/rules/

List of rule correspondence between different linters
https://docs.google.com/spreadsheet/ccc?key=0Ap5QGaRT4AJ_dGV6VXBlMEw3NHhVRl9vQ0lIX2FnVlE#gid=0

**Comment by rdpanek** [comment]
+1

**Comment by jr-duboc** [comment]
+1 Sound good to me

**Comment by mickaelandrieu** [comment]
yes and no.
We wont have time for this, but i will consider a complete PR ;)

**Comment by paazmaya** [comment]
PR already under construction...

**Comment by mickaelandrieu** [comment]
where? not linked to this issue in quick review

**Comment by paazmaya** [comment]
Has been merged
