### ISSUE TITLE
(Docs) Dead link in the casper#evaluate() section

### ISSUE THREAD

**Issue by petetnt** [n1k0/casperjs#1152]
In the section casper#evalute() there's a link that points to [https://github.com/ariya/phantomjs/wiki/API-Reference#wiki-webpage-evaluate](PhantomJS wiki) which doesn't exist anymore (it just prompts the user to create a wiki-page). Current/correct url would be [http://phantomjs.org/api/webpage/method/evaluate.html](http://phantomjs.org/api/webpage/method/evaluate.html)

**Comment by n1k0** [comment]
Thanks for the report. Could you please file a PR with the proper fix? Thanks in advance.

**Comment by petetnt** [comment]
Done!

**Comment by n1k0** [comment]
Thanks!
