### ISSUE TITLE
Add compatibility with Phantomjs 2.0 for windows

### ISSUE THREAD

**Issue by sireneweb** [n1k0/casperjs#1159]
Hi,
thanks for you great plugin, could you add compatibility with Phantomjs 2.0 for Windows ?

i get this error message :
CasperJS needs PhantomJS v1.x
Bootstrap.js:91 in __die

**Comment by czekFREE** [comment]
The same problem here...

**Comment by sumanta-ghosh** [comment]
I also face same problem
![capture](https://cloud.githubusercontent.com/assets/2699051/6276403/8c403238-b8ac-11e4-8b0f-2d1e1de78cc2.PNG)

**Comment by rdpanek** [comment]
You can use casperjs in image via docker https://registry.hub.docker.com/u/rdpanek/casperjs/

**Comment by paazmaya** [comment]
The roadmap is currently looking at `1.x` supporting PhantomJS `1.9.x`, and from `2.0` the PhantomJS `2.0` will be supported.
#987 #1150

**Comment by masi** [comment]
But PhantomJS 1.9.x has several issues and the PhantomJS guys do not seem to be addressing any remaining issues (incl. regressions) for 1.9.x.

**Comment by sireneweb** [comment]
Don't forget to update documentation and add test because with sample.js 
`
var casper = require('casper').create();

casper.start('http://casperjs.org/', function() {
    this.echo(this.getTitle());
});

casper.thenOpen('http://phantomjs.org', function() {
    this.echo(this.getTitle());
});

casper.run();
`
if i do this casperjs test sample.js, i got an error

![image](https://cloud.githubusercontent.com/assets/1773161/6776976/7e62a2f2-d145-11e4-8494-9df7b77542fe.png)

**Comment by paazmaya** [comment]
PR for documentation is more than welcome, on both `master` to reflect the issue with CasperJS `1.1` and PhantomJS `1.9`, and for `phantomjs-2` branch for `2.0` on both.

**Comment by mboiron** [comment]
Hi, I also get this error on windows : 

C:\Users\MBN\Documents\CasperFun>casperjs sample.js
Message d'erreur
Message d'erreur

It obviously doesn't collect the title of the page. Any help ?

Thanks

**Comment by istr** [comment]
This duplicates #1411 and will be addressed by means of #1365. Closing in favor of the more recent official release notice.
