### ISSUE TITLE
Python bin doesn't support path with spaces

### ISSUE THREAD

**Issue by Philoozushi** [n1k0/casperjs#1165]
When python bin file is in a path containing spaces
(typically with npm, e.g. `~/My Project/node_modules/casperjs/bin/casperjs`),
the `CASPER_COMMAND` becomes `['~/My', 'Project/node_modules/casperjs/bin/casperjs']`
because of `ENGINE_EXECUTABLE.split(' ')` in line 127.
Obviously, we get a `not found` error.

**Comment by Philoozushi** [comment]
Yeah, several tries for the fix :stuck_out_tongue:
This is my first time trying to fix / do pull requests with github, and trying to respect the guidelines.

**Comment by paazmaya** [comment]
Fixed via merge 922262747c7ec972cf48a4df5ce7942774dbbcbd
