### ISSUE TITLE
test fail 

### ISSUE THREAD

**Issue by Nuruddinjr** [n1k0/casperjs#1167]
```javascript
var casper = require('casper').create();

casper.begin('Testing Google', 1, function(test){
    casper.start('http//:google.com');

    casper.then(function(){
        test.assertTitle('Google', 'Google has correct title');
    });

    capser.run(function(){
        test.done();
    })
});

```

here i have the code but i am getting error as following Fatal: you can't override the preconfigured casper instance in a test environment.

**Comment by cosmo0920** [comment]
I had the same mistake! XD

This is because that Casper.js forbits override the preconfigured `casper` instance.
It seems that it needn't following line in test:

```js
var casper = require('casper').create();
```

So, following test code is correct:

```js
casper.test.begin('Testing Google', 1, function(test){
    casper.start('http://google.com');

    casper.then(function(){
        test.assertTitle('Google', 'Google has correct title');
    });

    casper.run(function(){
        test.done();
    })
});
```

**Comment by paazmaya** [comment]
@Nuruddinjr was the documentation unclear for this given use case?
If yes, any suggestion on how it could be improved?
