### ISSUE TITLE
Travis Help

### ISSUE THREAD

**Issue by jefleponot** [n1k0/casperjs#1179]
Hi,

What can I do when PR makes "modules/clientutils.js: line 43, col 47, This function has too many statements" ?

Regards

**Comment by paazmaya** [comment]
Can you be a bit more specific, perhaps a link to the given Travis build if possible?

**Comment by jefleponot** [comment]
Hi paazmaya,

Thanks for you solicitude.

I try to do a new PR , but it always give me 2 errors on jshint test :
https://travis-ci.org/n1k0/casperjs/jobs/53980633

**Comment by paazmaya** [comment]
The errors you are seeing are from JSHint, which is used to validate the JavaScript code.

You can run it locally after installing it with `npm i -g jshint`,

```sh
jshint .
```

**Comment by paazmaya** [comment]
Ouh yes, and to fix those, you would need to reduce the amount of parameters and statements as described in the messages

**Comment by jefleponot** [comment]
I just have a look to your gitBook  "Modern Web tools with Node.js". it's brillant. Very good job. 
I'm really a begginer

**Comment by jefleponot** [comment]
How many parameters could I use ? 4 / 5 
With modules/clientUtils.js do I erase some Functions or Create a new file to do the same features ?

Is there any configuration possible to change limit parameters for jshint ?

**Comment by jefleponot** [comment]
paazmaya,

I just install locally jshint but I have not the same errors:

bin/bootstrap.js: line 87, col 10, This function's cyclomatic complexity is too high. (11)

modules/casper.js: line 411, col 48, This function's cyclomatic complexity is too high. (9)
modules/casper.js: line 803, col 46, This function's cyclomatic complexity is too high. (8)
modules/casper.js: line 1342, col 36, This function's cyclomatic complexity is too high. (8)
modules/casper.js: line 1416, col 38, This function's cyclomatic complexity is too high. (11)
modules/casper.js: line 1555, col 44, This function's cyclomatic complexity is too high. (9)
modules/casper.js: line 1619, col 37, This function's cyclomatic complexity is too high. (8)
modules/casper.js: line 1718, col 40, This function's cyclomatic complexity is too high. (9)
modules/casper.js: line 2353, col 64, This function has too many parameters. (6)

modules/clientutils.js: line 310, col 34, This function's cyclomatic complexity is too high. (11)
modules/clientutils.js: line 648, col 66, This function's cyclomatic complexity is too high. (8)
modules/clientutils.js: line 696, col 67, This function's cyclomatic complexity is too high. (8)
modules/clientutils.js: line 940, col 42, This function's cyclomatic complexity is too high. (9)
<b>modules/clientutils.js: line 43, col 47, This function has too many statements. (44)</b>

Please Help Me

**Comment by paazmaya** [comment]
@jefleponot did you manage to solve those issues?

There is a #1133 waiting to be merged and it will offer better visibility on the linting errors

**Comment by jefleponot** [comment]
Hi @paazmaya

I solve  "waiting to be merged and it will offer better visibility on the linting errors" in creating a closure.
but "This function's cyclomatic complexity is too high" issue is always here.

**Comment by paazmaya** [comment]
Well the way to fix the given lint error, is to make the function simpler, perhaps by splitting it to a two functions.

Here is the documentation for the rule http://eslint.org/docs/rules/complexity
Please see the related links at the bottom to help you get forward.

**Comment by jefleponot** [comment]
thanks paazmaya.
I could refactor next week.

**Comment by paazmaya** [comment]
Is this issue with Travis solved?

**Comment by istr** [comment]
@jefleponot This issue seems to be obsolete to me, since @paazmaya moved to using eslint and the code is annotated, so that travis build will pass (be it with lots of lint warnings, though). Closing. Feel free to re-open if your issue is still relevant.
