### ISSUE TITLE
How pass capser self to evaluate function 

### ISSUE THREAD

**Issue by paul2008** [n1k0/casperjs#1190]
I want to save image in webpage environment .
casper.thenEvaluate(function then(fn) {
		console.log(typeof(fn));// <-- print 'function'
		fn('c:\\aa.png');//<-- doesn't work		
	},casper.capture);

page.Error: TypeError: 'undefined' is not a function (evaluating 'this.checkStarted()');

How to do.Thanks.

**Comment by n1k0** [comment]
You can't pass functions to `evaluate` as they're not serializable.

**Comment by paul2008** [comment]
Now,How to capture image ,and scrap page content in webpage environment. I want to debug it.

Acturally, My Code is:
caper.evaluation(function (){
    setInterval(timer,5000);
    
    function timer(){
        // I want to capture image and scrap page content, because this time is needed for debug.
    }
})
