### ISSUE TITLE
(Windows) Enable ANSI colors if the user is using ConEmu

### ISSUE THREAD

**Issue by petetnt** [n1k0/casperjs#1193]
Kinda platform specific, but as there is already support for `ANSICON`, I figured why not.

[ConEmu](https://code.google.com/p/conemu-maximus5/) is a popular Windows Console Emulator that has support for `ANSI X3.64 and Xterm 256 colors`. 

I sent PR #1192 which checks if the user is using ConEmu and has the ANSI colors enabled via `ConEmuANSI` `env`-variable.

**Comment by paazmaya** [comment]
@petetnt why was the PR closed?

**Comment by petetnt** [comment]
Accidentally made the PR from wrong branch and then duped it to #1199.
#1199 is the correct one, but the build failed because some `apt-get` repo
for `mono` didn't respond in time. :8ball:

2015-04-09 9:04 GMT+03:00 Juga Paazmaya <notifications@github.com>:

**Comment by paazmaya** [comment]
I tried re-running it but failed in the same spot.
Could you try getting the latest changes from `master` to your #1199 as #1201 had something to do with it?

**Comment by petetnt** [comment]
Merged with the current `master` and now the tests pass!

2015-04-09 12:14 GMT+03:00 Juga Paazmaya <notifications@github.com>:
