### ISSUE TITLE
Why CasperJS and browsers show different behaviors with CAPTCHA?

### ISSUE THREAD

**Issue by zjiash** [n1k0/casperjs#1198]
I'm using CasperJS to automate some of my tasks. 
CasperJS will meet captcha when exploring web pages. However, when I use browsers (chrome and safari) to access the page, I don't need to input the captcha. I try to set the `userAgent` option with the same value in browsers, but it does not work.
I want to know why CasperJS and browsers show different behaviors. Thanks.

**Comment by n1k0** [comment]
Please address support requests to the [mailing-list](https://groups.google.com/forum/?fromgroups=#!forum/casperjs). Thanks for your understanding.
