### ISSUE TITLE
How to capture image ,and scrap page content in webpage environment

### ISSUE THREAD

**Issue by paul2008** [n1k0/casperjs#1200]
Now,How to capture image ,and scrap page content in webpage environment. I want to debug it.

Acturally, My Code is:
```javascript
caper.evaluation(function (){
    setInterval(timer,5000);    
    function timer(){
        //capser.caputre...
        // I want to capture image and scrap page content at this time, because this time is needed for debug.
    }
})
```

**Comment by n1k0** [comment]
Please address support requests to the [mailing-list](https://groups.google.com/forum/?fromgroups=#!forum/casperjs). Thanks for your understanding.
