### ISSUE TITLE
Keep Support For Coffeescript With PhantomJS 2.0

### ISSUE THREAD

**Issue by timscott** [n1k0/casperjs#1203]
To my horror, PhantomJS 1.9 stopped working for me on a certain website. To my delight, PhantomJS 2.0 fixes it. But then to my horror again, apparently PhantomJS has dropped support for Coffeescript.

https://github.com/ariya/phantomjs/issues/12410

It seems my choices are:

 1. Add add a compile step (with cake, I guess) on deployment. In development, manually compile after every code change (ouch!).
 2. Convert my thousands of lines of existing Coffeescript to JS, and leave Coffeescript behind (double ouch!).

I guess there is a third choice: somehow compile at runtime. I guess I can find a way to do this in my app before calling CasperJS. However, I wonder if there is way to add this step to CasperJS. It would invoke whenever the file is Coffescript and PhantomJS is >= 2.0.

Is that is possible? Is it desired? If desired, where would the code go? I'm guessing somewhere around [here](https://github.com/n1k0/casperjs/blob/master/bin/bootstrap.js#L127)?

I would be willing to take this on if it's desired. I must solve it for myself asap.

**Comment by petetnt** [comment]
For workaround number 1 you could use something like [grunt-contrib-coffee](https://github.com/gruntjs/grunt-contrib-coffee) with [grunt-contrib-watch](https://github.com/gruntjs/grunt-contrib-watch) to automatically compile the .coffee files after every code change.

**Comment by timscott** [comment]
I'm running CasperJS from a Ruby on Rails app. It turns out to be pretty easy because the ```coffee-rails``` gem gives me ```CoffeeScript.compile``` (via the ```ruby-coffee-script``` gem).

I created a little runtime build system that compiles the script and all possible dependencies just before it's executed. It build only once in production and every time in other environments.

It solves my issue nicely, but it would be even nicer if CasperJS would handle it. The most valuable coding work is done with the delete key!

**Comment by paazmaya** [comment]
It is less burden for a project such as CasperJS to reduce the amount of dependencies, here namely CoffeeScript, in similar way as PhantomJS did.

Would @timscott be willing to create a PR for documentation against the `phantomjs-2` branch, where he could share how his setup was done?

**Comment by BIGjuevos** [comment]
These have been documented with #1510.  Closing issue.

@timscott We would love it if you could share your findings in the [new cookbook](http://docs.casperjs.org/en/latest/cookbook.html), or even just drop us a link to the gist so we can integrate it.

**Comment by timscott** [comment]
Okay, I extracted my code to something reusable: https://gist.github.com/timscott/636f641fe22046695bf0705bd36b92a7
