### ISSUE TITLE
Error handling horribly broken when using PhantomJS 2.0

### ISSUE THREAD

**Issue by jdunk** [n1k0/casperjs#1204]
I'm very surprised to apparently be the first one to report this, > 2 months after PhantomJS 2.0's official release, but it appears that error handling is horribly broken when using PhantomJS 2.0.

For example, when using PhantomJS 2.0.0 with the casperjs `phantomjs-2` branch (commit `d211035`), executing the following test code:

```
var casper = require('casper').create();
foo.bar();
```

...results only in **indefinite hanging**.  Absolutely no output at all. And on my mac, Activity Monitor reports CPU usage > 100% and 1.24GB memory usage.  This remains until I kill the process.  Same exact result on my Ubuntu server.

I tried adding an error handler, which apparently has no effect whatsoever:

```
casper.on('error', function(err) {
    console.log('on error handler called');
    this.die("Error: " + err);
});
```

## Expected Result

For comparison, what happens when using casperjs 1.1.0-beta3 with PhantomJS 1.9.8 and executing the exact same test code above is the following output:

```
ReferenceError: Can't find variable: foo                                        
  /Users/ap/scripts/fc/test-error.js:2
```

...and then it exits.

**Comment by istr** [comment]
The problematic part of the code is commented out within [my 2.0.0 PR](https://github.com/n1k0/casperjs/pull/1352) to make error handling work with 2.0.0.

**Comment by istr** [comment]
Closed with [PR 1352](https://github.com/n1k0/casperjs/pull/1352).
