### ISSUE TITLE
casper.fetchText() will often return the string "undefined"

### ISSUE THREAD

**Issue by justinklemm** [n1k0/casperjs#1206]
A PR was merged on [Nov 3rd, 2014] (https://github.com/n1k0/casperjs/commit/bb706acdf38f30d2380ebd3897ba1d4cee74430c) from @andy-g that updated the fetchText() function to [also check the element's value attribute](https://github.com/n1k0/casperjs/commit/bb706acdf38f30d2380ebd3897ba1d4cee74430c) (when the inner text/html is empty) -- which was a nice improvement! However, if the OR logic makes it to `element.value` and the value attribute is undefined (as it often is for non-input elements), then the result ends up being the string "undefined", instead of an empty string.

For example, if you have `<p id="test"></p>`, the result of `casper.fetchText('#test')` will be the string "undefined", not "". (This appears to be the result of JavaScript converting an undefined value to a string.)

A quick fix would be to amend the logic like so:

`text += element.textContent || element.innerText || element.value || '';`

I'm happy to create a PR to fix this and/or a test proving the above, I just wanted to run it by you guys first.

**Comment by paazmaya** [comment]
Thank you for noticing this.

Can you please create a PR which also adds tests for this?

**Comment by andy-g** [comment]
Thanks for picking that up @justinklemm, hadn't thought of that when I submitted my PR.

**Comment by justinklemm** [comment]
No prob, guys. I'll submit a PR tomorrow with the fix above and tests demonstrating it.

**Comment by justinklemm** [comment]
Ok, PR submitted with the fix and a test. (If you add that test to the current code base, you'll see that it fails.)

Let me know if you need anything else from me. Thanks!
