### ISSUE TITLE
Missing documentation on Casper.options callbacks

### ISSUE THREAD

**Issue by mixmatch** [n1k0/casperjs#1208]
I can find no parameter information/examples on the following callbacks:
onAlert
Type: Function
Default: null
A function to be called when a javascript alert() is triggered

onDie
Type: Function
Default: null
A function to be called when Casper#die() is called

onError
Type: Function
Default: null
A function to be called when an “error” level event occurs

onLoadError
Type: Function
Default: null
A function to be called when a requested resource cannot be loaded

onPageInitialized
Type: Function
Default: null
A function to be called after WebPage instance has been initialized

onResourceReceived
Type: Function
Default: null
Proxy method for PhantomJS’ WebPage#onResourceReceived() callback, but the current Casper instance is passed as first argument.

onResourceRequested
Type: Function
Default: null

Proxy method for PhantomJS’ WebPage#onResourceRequested() callback, but the current Casper instance is passed as first argument.

onStepComplete
Type: Function
Default: null
A function to be executed when a step function execution is finished.

onStepTimeout
Type: Function
Default: Function
A function to be executed when a step function execution time exceeds the value of the stepTimeout option, if any has been set.

By default, on timeout the script will exit displaying an error, except in test environment where it will just add a failure to the suite results.

onTimeout
Type: Function
Default: Function
A function to be executed when script execution time exceeds the value of the timeout option, if any has been set.

By default, on timeout the script will exit displaying an error, except in test environment where it will just add a failure to the suite results.

onWaitTimeout
Type: Function
Default: Function
A function to be executed when a waitFor* function execution time exceeds the value of the waitTimeout option, if any has been set.

By default, on timeout the script will exit displaying an error, except in test environment where it will just add a failure to the suite results.

**Comment by mixmatch** [comment]
Also seeing what appear to be properties of the Casper object that are not in documentation (i.e. requestUrl)

**Comment by mixmatch** [comment]
casper.thenEvaluate(function(term) {});
casper.start().each(links, function(self, link) {});

**Comment by mixmatch** [comment]
https://github.com/n1k0/casperjs/pull/1209

**Comment by paazmaya** [comment]
The given PR was merged, hence closing
