### ISSUE TITLE
xpath selector error reports as [object Object] 

### ISSUE THREAD

**Issue by scottlabs** [n1k0/casperjs#1214]
Hi,

When doing something like this:

            var selector = {
                type: 'xpath',
                path: '//*[@class="plop"]'
            };
            var info = casper.getElementInfo(selector);

Where selector is an element that does not exist, the error reported looks like this:

`CasperError: Cannot get informations from [object Object]: element not found.`

It would be very helpful if the error reported the XPath selector path in the error, instead of `[object Object]`.

**Comment by scottlabs** [comment]
Here is a possible pull request that would address this:

https://github.com/n1k0/casperjs/pull/1215

**Comment by n1k0** [comment]
As commented on the PR, the correct usage as [documented](http://docs.casperjs.org/en/latest/selectors.html#index-2) to select XPath is:

```js
var x = require('casper').selectXPath;
…
var info = casper.getElementInfo(x('//*[@class="plop"]'));
```

That way you get proper error reporting.

**Comment by scottlabs** [comment]
`selectXPath` is only available under the testing environment, `casperjs test`, correct? i.e., running a script:

`casperjs script.js`

Throws the error `'undefined' is not a function` in reference to selectXPath.

**Comment by n1k0** [comment]
> selectXPath is only available under the testing environment, casperjs test, correct? 

Nope, as demoed above it's [properly exported](https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L66-L76) hence requirable in regular scripts as well:

```js
var x = require('casper').selectXPath;
```

Doesn't it work for you?

**Comment by scottlabs** [comment]
Ah you're right @n1k0, I was doing something wrong. Thanks for the support!
