### ISSUE TITLE
Running casper without the pass output

### ISSUE THREAD

**Issue by rbalazs** [n1k0/casperjs#1216]
Could you recommend a way of running casper to show the warnings/errors, but hide all the "Pass" messages? 
Thanking you in advance!

**Comment by mefiblogger** [comment]
+1

**Comment by mefiblogger** [comment]
This option is doing the business:

`--concise`

Here you can find around the "What's new in 1.0.0" section:

http://casperjs.readthedocs.org/en/latest/testing.html

**Comment by rbalazs** [comment]
Merci beaucoup, mate! :-)
