### ISSUE TITLE
Cannot require local scripts while using the slimerjs engine

### ISSUE THREAD

**Issue by Mike-Now** [n1k0/casperjs#1229]
1 Create test scripts like so:
http://casperjs.readthedocs.org/en/latest/writing_modules.html
2 Run the test script : 
casperjs --engine=slimerjs test.js
3 Output :

        Script Error: Module: Can not resolve "./universe" module required by main located at
    file:///xxx/scraper/node_modules/casperjs/bin/bootstrap.js
       Stack:
         -> file:///xxx/scraper/node_modules/casperjs/bin/bootstrap.js: 350

Note : slimerjs version: 0.9.5. The test script *does* work with phantomjs 1.9.8

**Comment by psyvisions** [comment]
```
var require = patchRequire(require);
var universe = require('universe');
```

**Comment by Mike-Now** [comment]
Well, it only works for me when I provide the absolute path to universe.js.

**Comment by Mike-Now** [comment]
After more tests:

-casperjs with slimerjs - doesn't work
-casperjs with phantomjs - works
-pure slimerjs - works

**Comment by Mike-Now** [comment]
I managed to patch it by commenting out the line(384) in file casperjs/bin/bootstrap.js

    if ("slimer" in global && phantom.casperScriptBaseDir) {
        // initCasperCli has set casperScriptBaseDir
        // use it instead of fs.workingDirectory
        // require.paths.pop(); <--- commented out
        require.paths.push(phantom.casperScriptBaseDir);
    }

**Comment by Mike-Now** [comment]
The newest commit on the master branch  (376d85fceb5eca63596e12e2ef6072a72422ed9b) has this issue fixed.
