### ISSUE TITLE
ask a question

### ISSUE THREAD

**Issue by gitlsl** [n1k0/casperjs#1266]
i like this project and i want to know which editor used to write script?
thank you for your help!

**Comment by mixmatch** [comment]
https://atom.io/ ?

**Comment by gitlsl** [comment]
does it has code completion?

**Comment by akshay-padalkar26** [comment]
For spell checking, 
is there any library avaliable for casperjs?

**Comment by amerikan** [comment]
@gitlsl This type of question is probably best for the mailing list: http://groups.google.com/group/casperjs.

@istr probably can be closed

**Comment by istr** [comment]
Closing. Thanks @amerikan :-)
