### ISSUE TITLE
CasperError: Errors encountered while filling form: RangeError: Array size is not a small enough positive integer.

### ISSUE THREAD

**Issue by Lucas-C** [n1k0/casperjs#1275]
Hello,

This is a bug report : I identified the root cause of the error mentioned in this issue title.
When trying to fill a form, I was passing an integer as a password and the following code crashed because `value.length` evaluated to `undefined`:
https://github.com/n1k0/casperjs/blob/master/modules/clientutils.js#L828

I guess either `value` should be checked or converted to string at some point beforehand,
or this code line should handle non-string values.

    $ casperjs --version && phantomjs --version
    1.1.0-beta3
    1.9.8

**Comment by timscott** [comment]
I just got this. Workaround?

**Comment by Lucas-C** [comment]
Convert the integer to string:

    ''+42

**Comment by istr** [comment]
Merged. Thanks for your PR.
