### ISSUE TITLE
Any ideas?  CasperJS not working with <noscript> tag...

### ISSUE THREAD

**Issue by sawteeth** [n1k0/casperjs#1304]
I'm using CasperJS to scrape a website.  The page source has a `<noscript>` tag, and therefore is not showing the page I need to scrape, because it claims I don't have JavaScript enabled.

`javascriptEnabled` is `true` by default in CasperJS, but I added it to my initialization anyway, to no avail.

Any work arounds to fix this issue?  It might also be an issue with PhantomJS...

**Comment by cosmo0920** [comment]
Please show your code, or minimal reproduce code?
If show your code that reproduces this problem, someone may help you easier.

**Comment by TESTGITHUBACCOUNT2** [comment]
There is no code to show, really...

The HTML page has

```html
<noscript>
asdfasdf
</noscript>
```

**Comment by cosmo0920** [comment]
Actually, I want you show your scraping code.
If you do not want to show full your code, I hope you to show **minimal reproduce code**.

**Comment by TESTGITHUBACCOUNT2** [comment]
@cosmo0920 no like there's literally no scraping code...  I'm just opening a URL:

```nodejs
casper.start();
casper.thenOpen(url);
casper.run();
```

**Comment by cosmo0920** [comment]
Hmm..., it is lack of information about your environment and steps to reproduce....

**Comment by sawteeth** [comment]
Again, there is no information required to produce...

Create an HTML page, and add the following:

```html
<noscript>
Javascript not enabled.
</noscript>
```.

Then, access the page via Casper:

```nodejs
casper.start();
casper.thenOpen(url);
casper.run();
```

 Then, `casper.capture('image.png');` the contents.  You should get an image of "No Javascirpt available"...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript

**Comment by sawteeth** [comment]
@cosmo0920 for some reason the webpage thinks JavaScript isn't enabled...

**Comment by cosmo0920** [comment]
Above html contains `<title>` tag and `<p>` or other tags?

I try to following HTML to reproduce this issue.
But, sadly, I couldn't reproduce this issue.

~/work/test-scraping.html
```html
<html>
<title>no script test</title>
<noscript>
Javascript not enabled.
</noscript>
<p>no script test</p>
</html>
```

And I use following javascript code:

~/work/test-scraping.js
```js
var casper = require('casper').create();
var system = require('system');
var home = system.env.HOME;

casper.start('file:////' + home + '/work/test-scraping.html', function() {
    this.echo(this.getTitle());
    this.capture('local.png');
});
casper.run();
```

Run it:

```log
$ casperjs test-scraping.js --verbose --log-level=debug --ignore-ssl-errors=true
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: file://///Users/hhatake/work/test-scraping.html, HTTP GET
[debug] [phantom] Navigation requested: url=file://///Users/hhatake/work/test-scraping.html, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "file://///Users/hhatake/work/test-scraping.html"
2015-08-26 14:41:28.974 phantomjs[15531:110b] CoreText performance note: Client called CTFontCreateWithName() using name "Times New Roman" and got font with PostScript name "TimesNewRomanPSMT". For best performance, only use PostScript names when calling this API.
2015-08-26 14:41:28.975 phantomjs[15531:110b] CoreText performance note: Set a breakpoint on CTFontLogSuboptimalRequest to debug.
[debug] [phantom] Successfully injected Casper client-side utilities
no script test # can get page title
[debug] [phantom] Capturing page to /Users/hhatake/work/local.png
[info] [phantom] Capture saved to /Users/hhatake/work/local.png
[info] [phantom] Step anonymous 2/2: done in 128ms.
[info] [phantom] Done 2 steps in 128ms
```

And then I can get this page screenshot:

![local](https://cloud.githubusercontent.com/assets/700876/9486350/ee75a824-4c00-11e5-9eb8-404709eb2044.png)

**Comment by sawteeth** [comment]
Ok that is very weird... The website I keep trying to access tells me I do not have JavaScript enabled through the same method and so it doesn't load content.... I have no problem in web browser and I never told anything to turn off JavaScript...

**Comment by sawteeth** [comment]
Also I should mention I can see page title...

**Comment by rippo** [comment]
Not sure if it will make a difference but try changing the user agent

Sent from my Windows Phone
________________________________

**Comment by sawteeth** [comment]
@rippo cool thanks.  Is there anywhere I can find a list of them that duplicated browsers?

**Comment by rippo** [comment]
Urmm just sniff your own browser user fiddler. Or I am sure there must be a web site that lists these things

Sent from my Windows Phone
________________________________

**Comment by sawteeth** [comment]
Changing user agent did nothing: 
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36

**Comment by sawteeth** [comment]
Ok this issue has been fixed -- I did the following, if anyone has any questions.  The HTML was rendered by the JavaScript, which took a long time to load, so open it like you would normally in a browser, and find an element that only appears when the javascript loads -- note doing view source doesn't work you have to inspect element (you get current DOM).

I then did:

```nodejs
casper.waitForSelector('.SOME_CLASS', function() {
    this.echo(this.getHTML('.SOME_CLASS'));
    this.echo(this.getElementInfo('.SOME_CLASS').text);
});
```

This allows the page to stop and load the javascript.  IF anyone has a similar issue, let me know.
