### ISSUE TITLE
Using NPM modules in file run with CasperJS

### ISSUE THREAD

**Issue by sawteeth** [n1k0/casperjs#1305]
I know that CasperJS isn't usable with node directly, but can I not even use a service like `cheerio`, a node web scraping tool?

I tried `require('cheerio');` and it said not found.  So, I did:

**proxies/cheerios.js**
```js
module.exports = require('cheerio');
```

**tests/file.js**
```js
var cheerio = require('../proxies/cheerio.js');
```

Now, I get:
> Error: Cannot find module 'util'
> phantomjs://bootstrap.js:289
> phantomjs://bootstrap.js:254 in require

Any suggestions?  I really need to use this plugin in CasperJS, and SpookyJS isn't working...

**Comment by istr** [comment]
Probably the problem is with your invocation of CasperJS or the module is not compatible with CasperJS.  Please "Note that CasperJS is not capable of using a vast majority of NodeJS modules out there. **Experiment and use your best judgement.**" (updated documentation in the upcoming 1.1.0-beta4).
