### ISSUE TITLE
npm install should add phantomjs to path

### ISSUE THREAD

**Issue by andrewnguyen42** [n1k0/casperjs#1307]
this seems like a pretty reasonable step to take on windows and linux since the phantomjs binaries already get expanded during the casperjs install

**Comment by istr** [comment]
I am closing this because starting with 1.1.0-beta4 we will drop auto-installation of the engine. The choice of the correct engine is a bit peculiar, so we stick with installation instructions which versions are supported and leave the installation / choice to the user.
