### ISSUE TITLE
Modify isJsFile() to detect if CoffeeScript is a valid filetype

### ISSUE THREAD

**Issue by hexid** [n1k0/casperjs#1309]
I've been looking into how we could keep Coffeescript support for PhantomJS v1.x and SlimerJS, while possibly adding support for PhantomJS v2.x.

So far, I've found that `require.extensions` holds the possible filetypes that the engine can support when being required, which should roughly match those that are available to be used with `phantom#injectJs()`

PhantomJS v2.0:

    {
        ".js": "[Function]",
        ".json": "[Function]"
    }

PhantomJS v1.9.8 / SlimerJS 0.9.6:

    {
        ".coffee": "[Function]",
        ".js": "[Function]",
        ".json": "[Function]"
    }

I've written a patch that uses the file extensions above (without `.json`) to allow `isJsFile()` from utils.js to determine the correct filetypes based on the engine.
I'll submit a PR when I have the time to thoroughly test the patch on each of the engines.

This allows PhantomJS v2.x to ignore the CoffeeScript tests, allowing us to keep them around for testing SlimerJS and PhantomJS v1.x

**Comment by web-connect** [comment]
Beat me by 3 hours. I support a solution like this

**Comment by n1k0** [comment]
> This allows PhantomJS v2.x to ignore the CoffeeScript tests, allowing us to keep them around for testing SlimerJS and PhantomJS v1.x

Thanks for taking the time to dig into this. I think keeping cs compatibility is important for casperjs users.

**Comment by istr** [comment]
I think this is closed with your merged PR https://github.com/n1k0/casperjs/pull/1310 in current master, see  https://github.com/n1k0/casperjs/blob/master/modules/utils.js#L467.

Please re-open if I am wrong.
