### ISSUE TITLE
CasperJS needs PhantomJS v1.x

### ISSUE THREAD

**Issue by ardiiem** [n1k0/casperjs#1312]
Hi All,

I have encountered an error as I have tested the CasperJS and PhantomJS.

I got the error below.
CasperJS needs PhantomJS v1.x
C:\casperjs\batchbin\..\bin\bootstrap.js:91 in__die

Could you guys help me with this issue?

Thanks in advance! :)

**Comment by cosmo0920** [comment]
It seems to be duplicated to #987.
Currently, CaspeJS does not support PhantomJS 2.0 yet.
Work in progress #1310.

**Comment by istr** [comment]
Closed with https://github.com/n1k0/casperjs/pull/1310 and https://github.com/n1k0/casperjs/pull/1352.

Note, however that support for phantomjs 1.9.0 and earlier is dropped.
