### ISSUE TITLE
Infinite loop on evaluate()

### ISSUE THREAD

**Issue by azamat-sharapov** [n1k0/casperjs#1316]
```js
casper.on('page.initialized', function() {
	this.evaluate(function(){})
})

var url = 'http://localhost:9000/'

casper.test.begin('The Test', function(test) {
	casper.start()

	casper.thenOpen(url, function() {
	})

	// one more time, open same page
	casper.thenOpen(url, function() {
	})

	casper.run(function() {
		test.done()
	})
})
```

I have code exactly looking like above. When I run `casperjs test thefile.js` I get unlimited number of phantomjs warnings (`Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.`).  
I have to break that infinite warning loop via `CTRL+C`, otherwise CPU consumption rises to 100%.

*I need to evaluate bind() polyfill for phantom on every page initialization, so I'm trying this. If there is another way to do that, please let me know, because it's currently unusable :(*

**Comment by azamat-sharapov** [comment]
Downgrading phantom from v1.9.8 to v1.9.7 solved issue, not sure why..

**Comment by istr** [comment]
This is a [known PhantomJS regression](https://github.com/ariya/phantomjs/issues/12697).
