### ISSUE TITLE
FAIL TypeError: Attempted to assign to readonly property

### ISSUE THREAD

**Issue by halidov** [n1k0/casperjs#1321]
Hello everyone!
I have started to use casperjs 1.1.0-beta3 and phantomjs 2.0 since that I get an infinite errors loop at every test fail. 
Example:
type: uncaughtError
file: /var/www/.. 
error: "Something" did not appear in the page in 5000ms
stack: not provided
FAIL TypeError: Attempted to assign to readonly property.
 type: uncaughtError
 file: /var/www/...
 error: Attempted to assign to readonly property.
at 
at 
at 
at 
at 
at 
at 

Can you please give me right direction how I could solve this issue?

**Comment by ebordeau** [comment]
I'm seeing the same thing.

**Comment by ohenak** [comment]
I have seen this two times,
Once when I was trying to extend the `test` module.
Second when the number of test cases you mentioned in the `casper.test.begin()` doesn't match the number of assertions you have in the test.

Hope this help.

**Comment by istr** [comment]
@halidov Could you please re-check with the latest versions? (i.e. CasperJS 1.1.0-beta5 and PhantomJS 2.1.1)

Thank you!

**Comment by halidov** [comment]
@istr I have just checked it out and everything's ok, guess bug fixed. Thank you!

**Comment by istr** [comment]
Closing. CasperJS 1.1.0-beta3 does not support PhantomJS 2.0 and later versions fix this.
