### ISSUE TITLE
XUnit tests in Gecko (SlimerJS) defaulting to XHTML namespace + potential fix

### ISSUE THREAD

**Issue by DrCuriosity** [n1k0/casperjs#1322]
When generating XUnit test results using the SlimerJS engine, I'm getting an erroneous XHTML namespace attribute turning up in my test output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<testsuites xmlns="http://www.w3.org/1999/xhtml" time="86.138">
  <testsuite name="[AC1]" tests="1" failures="0" errors="0" time="3.488" timestamp="2015-09-21T02:55:41.984Z" package="[redacted]">
    <testcase name="HTTP status code is: 200" classname="[redacted]"></testcase>
    <system-out></system-out>
  </testsuite>
</testsuites>
```

I'm using version 1.1.0-beta3, patched with the pull request from #759 to get it serializing properly.

The problem seems to be that `XMLSerializer` defaults to an XHTML namespace for `document.createElement()`. Tracing that back to ```utils.node()```, I've fixed it locally with the following:

```patch
714c714
<     var _node   = document.createElement(name);
---
>     var _node   = document.createElementNS('', name);
```

Since digging this far into the DOM is a bit arcane for me, is this the right way to go about fixing the problem? I thought about doing a ```string.replace()``` on the output of the serialization in ```xunit.js```, but that didn't feel like the right place to be doing it.

**Comment by DrCuriosity** [comment]
This issue persists into 1.1.0-beta5. The fix above gets the output parsing properly in my Jenkins CI rig.

**Comment by istr** [comment]
Would you mind creating a PR for the proposed bugfix? The bugfix seems trivial, but I would like to have a proper PR for
- correct attribution of authorship
- four-eyes review
- automated testing of the fix

Thank you.

**Comment by DrCuriosity** [comment]
I was holding off on that until I was sure the fix was the right approach, rather than a kludge. I'll try to get a pull request sorted inside the next 24 hours.
