### ISSUE TITLE
nth-child(n) selector doesn't work

### ISSUE THREAD

**Issue by slavugan** [n1k0/casperjs#1325]
casper doesn't find element by selector with nth-shild: '#ctl00_plhMain_gvSlot tr:nth-child(3) a', but document.querySelector finds element well.

**Comment by hexid** [comment]
@slavugan Could you give some details on which which version of PhantomJS/SlimerJS you are using, along with your version of CasperJS?

**Comment by slavugan** [comment]
phantom 1.9.0, casper 1.1.0-beta3. Oh, it is rather the problem of the phantom than  the casper, sorry.
