### ISSUE TITLE
phantomjs v2

### ISSUE THREAD

**Issue by hayesmaker** [n1k0/casperjs#1327]
will this ever support v2 phantomjs? until then we're stuck with an ancient version of webkit, which doesn't even support es5

**Comment by hayesmaker** [comment]
nvm.. saw it's wip

**Comment by hexid** [comment]
@hayesmaker You can go ahead and try out my [experimental branch](https://github.com/hexid/casperjs/tree/phantomjs2-bc) until #1310 gets merged.

Most of the tests are passing, but it'll be difficult to determine what is broken until PhantomJS v2.0.1 is released as it should fix some of the regressions that are present in v2.0.0.
