### ISSUE TITLE
"Unsafe JavaScript attempt to access..." logged at random times.

### ISSUE THREAD

**Issue by nfriedly** [n1k0/casperjs#1330]
This error message seems to be appearing a lot:

    Unsafe JavaScript attempt to access frame with URL about:blank from frame with URL file:///usr/local/lib/node_modules/casperjs/bin/bootstrap.js. Domains, protocols and ports must match.

I've noticed a few different things that cause it to get logged to the console, including:

* Calling `this.exit()` from within the `onError` callback.
* Running `casperjs --version`
* Running `casperjs file-that-doesnt-exist` -- that logs it twice!

I'm on CasperJS v1.1.0-beta3.

**Comment by amerikan** [comment]
see #1068

**Comment by paazmaya** [comment]
Closing as duplicate
