### ISSUE TITLE
CasperJS seems not working with JSON response

### ISSUE THREAD

**Issue by tungpt87** [n1k0/casperjs#1339]
Hi development team,

Hope you have a good day!

I'm encountering a problem using CasperJS. It is I'm trying to connect to an API using GET method but Casper keeps responding me an empty HTML while the same code of mine with other URL (http://google.com) works properly. I tried the API using browser and it shows the data is not in HTML form but purely a JSON text so I guess that might be the problem. Below is my code:
```javascript
 var casper = require('casper').create({
	verbose:true,
	 logLevel: "debug",
	pageSettings: {
		webSecurityEnabled: false,
		ignoreSslErrors: false,
		userAgent:'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36'
	},
	onError: function(self, m) {
		createFile(m);
	},
	onLoadError: function(self, m) {
		createFile(m);
	}
});
casper.start();
var url = 'https://api.predicthq.com/v1/events/?id=e5c55724e854289204&access_token=[Access_Token]';
casper.open(url,{
	method:"GET",
});

casper.then(function(){
	try{
		console.log(this.status(true));
		console.log(this.getHTML());
	}
	catch(e) {
		console.log("ERROR INFO: "  + this.getHTML());
	}
});
casper.run();
```

And please find the image attached to see my attempt using Chrome Postman extension 

![capture](https://cloud.githubusercontent.com/assets/2960321/10783486/2e18ab2a-7d93-11e5-9009-3d29c4731499.PNG)

Hope that you can help me to find a solution for this situation!

I'm looking forward to your answer

Cheers,
Terry

**Comment by cmck** [comment]
Have you tried to set request headers and use getPageContent() rather than getHTML() http://docs.casperjs.org/en/latest/modules/casper.html#getpagecontent

**Comment by istr** [comment]
Please address these kind of questions to the mailing list first.

Yes, @cmck  using ```getPageContent()``` is the right solution, see https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/content.js#L21
