### ISSUE TITLE
Cannot pass single-item JSON as argument to evaluate()

### ISSUE THREAD

**Issue by vimagick** [n1k0/casperjs#1344]
```
// test.js

var casper = require('casper').create();

casper.start('about:blank', function() {

  var x = {
    'hello': 'world',
  };

  var y = {
    'hello': 'world',
    'foo': 'bar',
  };

  this.evaluate(function(arg) {
    __utils__.echo(JSON.stringify(arg));
  }, x);

  this.evaluate(function(arg) {
    __utils__.echo(JSON.stringify(arg));
  }, y);

}).run();
```

```
$ casperjs test.js
"world"
{"hello":"world","foo":"bar"}
```

As we can see:
- :x:  1st line is wrong
- :white_check_mark: 2nd line is right

**Comment by paazmaya** [comment]
Would you like to add a test case for this scenario, which would help to get it fixed?

**Comment by vimagick** [comment]
It maybe not a bug.

- https://github.com/n1k0/casperjs/blob/master/modules/casper.js#L704-L711
- https://github.com/n1k0/casperjs/blob/master/modules/utils.js#L741-L746
- https://github.com/n1k0/casperjs/blob/master/tests/suites/casper/evaluate.js#L36-L48

However, [ECMAScript][1] spec says "order of enumerating... is not defined".

[1]: http://www.ecma-international.org/publications/files/ECMA-ST/Ecma-262.pdf
