### ISSUE TITLE
Popup related tests fail / time out randomly.

### ISSUE THREAD

**Issue by istr** [n1k0/casperjs#1354]
Like [stated here](https://github.com/n1k0/casperjs/pull/1352#issuecomment-158881829) the selftests for popup functionality fail randomly.

This needs investigation and it should be checked if this is related to some of the other issues filed against popup functionality (#963, #978, #1095, #1174, #1303).

**Comment by jefleponot** [comment]
I can't manage to reproduce this bug : could you help me with a code, a version of browser or anything else.

**Comment by mepard** [comment]
I'm consistently getting a popup test failure with released PhantomJS 2.1.1. Interestingly, I consistently do not get the failure when I build PhantomJS in debug mode. This is on OS X 10.11.3 with Xcode 7.2.

Release:

	Test file: /Users/marc/Projects/NewStuff/casperjs-me/tests/suites/casper/popup.js
	# popup tests
	PASS popup tests (22 tests)
	PASS "popup.created" event is fired
	PASS "popup.created" event callback get a popup page instance
	PASS "popup.loaded" event is fired
	PASS "popup.loaded" is triggered when popup content is actually loaded
	PASS Casper.waitForPopup() waits for a popup being created
	PASS A popup has been added
	PASS A popup is a WebPage
	PASS Casper.withPopup() found a popup with expected title
	PASS Casper.withPopup() found a popup with expected text
	PASS Casper.withPopup() switched to popup as current active one
	PASS Casper.withPopup() has client utils injected
	PASS Casper.withPopup() can perform assertions on the DOM
	PASS Casper.withPopup() can perform assertions on the DOM using XPath
	PASS Casper.withPopup() has reverted to main page after using the popup
	PASS "popup.closed" event is fired
	PASS Popup is removed when closed
	PASS Casper.waitForPopup() waits for a popup being created
	PASS Casper.withPopup() can use a regexp to identify popup
	PASS Casper.withPopup() has reverted to main page after using the popup
	FAIL Popup is removed when closed
	#    type: assertEquals
	#    file: /Users/marc/Projects/NewStuff/casperjs-me/tests/suites/casper/popup.js
	#    subject: 1
	#    expected: 0
	PASS Casper.waitForPopup() waits when clicked on a link with target=_blank
	PASS Page title is: "CasperJS test form"

Debug build:

	Test file: /Users/marc/Projects/NewStuff/casperjs-me/tests/suites/casper/popup.js
	# popup tests
	PASS popup tests (22 tests)
	PASS "popup.created" event is fired
	PASS "popup.created" event callback get a popup page instance
	PASS "popup.loaded" event is fired
	PASS "popup.loaded" is triggered when popup content is actually loaded
	PASS Casper.waitForPopup() waits for a popup being created
	PASS A popup has been added
	PASS A popup is a WebPage
	PASS Casper.withPopup() found a popup with expected title
	PASS Casper.withPopup() found a popup with expected text
	PASS Casper.withPopup() switched to popup as current active one
	PASS Casper.withPopup() has client utils injected
	PASS Casper.withPopup() can perform assertions on the DOM
	PASS Casper.withPopup() can perform assertions on the DOM using XPath
	PASS Casper.withPopup() has reverted to main page after using the popup
	PASS "popup.closed" event is fired
	PASS Popup is removed when closed
	PASS Casper.waitForPopup() waits for a popup being created
	PASS Casper.withPopup() can use a regexp to identify popup
	PASS Casper.withPopup() has reverted to main page after using the popup
	PASS Popup is removed when closed
	PASS Casper.waitForPopup() waits when clicked on a link with target=_blank
	PASS Page title is: "CasperJS test form"

**Comment by jefleponot** [comment]
Hi @istr ,

I schedule 10 times the command "**casper selftest tests/suites/casper/popup.js**" :  3 crashs.

---------------------------------------
this bug was not difficult to find.
This random bug comes from a garbage collector event.

I don't know how to show it directly in source code . 
So here is a wonderful copy-paste from "**pagestack.js**":

```
/**
 * Cleans the stack from closed popup.
 *
 * @param  WebPage  closed  Closed popup page instance
 * @return Number           New stack length
 */
Stack.prototype.clean = function clean(closed) {
    "use strict";
    var closedIndex = -1;
    this.forEach(function(popup, index) {
        if (closed === popup) {                        <==== bug
            closedIndex = index;
        }
    });
    if (closedIndex > -1) {
        this.splice(closedIndex, 1);
    }
    return this.length;
};
```

we compare objects that could be destroy or re-allocated so popup is never clear from the list.
The next list browsing will crash because list contains an object without reference.

Here is a possible resolution : 
 
```
/**
 * Cleans the stack from closed popup.
 *
 * @param  WebPage  closed  Closed popup page instance
 * @return Number           New stack length
 */
Stack.prototype.clean = function clean(closed) {
    "use strict";
    var closedIndex = -1, closedIndexSecond = -1;
    this.forEach(function(popup, index) {
        if (closed === popup) {
            closedIndex = index;
        } else if (closed.title === popup.title && closed.windowName === popup.windowName) {
            closedIndexSecond = index;
        }
    });
    if (closedIndex > -1) {
        this.splice(closedIndex, 1);
    } else if (closedIndexSecond > -1) {
        this.splice(closedIndexSecond, 1);
    }
    return this.length;
};
```

I schedule 1000 times this solution with command "**casper selftest tests/suites/casper/popup.js**" : no crash at all.

**Comment by jefleponot** [comment]
I will make a PR if this solution is acted

**Comment by mickaelandrieu** [comment]
Hi @jefleponot,

thanks a lot for this complete explanation, I confirm that your code works well :)

ping @n1k0 can you take a quick look at it ? Sounds like a little but pragmmatic hack.

Mickaël

**Comment by istr** [comment]
:clap: Thanks @jefleponot. Great we have the root cause. Probably there will be a less "hacky" solution to handle this, simply checking if the reference still is valid...

**Comment by jefleponot** [comment]
LoL
I let you write a prettiest code. Javascript Object reference is outside my skills...sorry.
Is there any annoying :bug: to resolve before adding new features ?

jef

**Comment by BIGjuevos** [comment]
@istr I've got this duplicated in my local environment.  Looking into doing a cleaner implementation.

**Comment by BIGjuevos** [comment]
@istr @mickaelandrieu @n1k0 - See PR #1490

**Comment by istr** [comment]
The PR looks good.

**Comment by BIGjuevos** [comment]
@jefleponot Can you confirm the latest build fixes your issue?

@istr I think we are good to mark this issue resolved now.

**Comment by istr** [comment]
@BIGjuevos I'll wait for @jefleponot s confirmation before closing this, but I guess it is resolved now.

**Comment by jefleponot** [comment]
Hi @Istr, @BIGjuevos 

Great Job, your code is Brilliant.
Please merge it @istr .

**Comment by istr** [comment]
@jefleponot This was merged by @mickaelandrieu some days ago. Closing.
