### ISSUE TITLE
Move the hint for mailing list from CONTRIBUTING.md to README.md

### ISSUE THREAD

**Issue by istr** [n1k0/casperjs#1358]
It seems that lots of issues are related to support requests either installing casperjs or getting test scripts to run.

In CONTRIBUTING.md there is a hint that refers to the mailing list https://groups.google.com/forum/#!forum/casperjs.

However, users (esp. new users) are unlikely to read this document. It would be better to redirect them at a prominent position within README.md

**Comment by n1k0** [comment]
I agree. Whatever can help people reaching to right place to get appropriate support is good to have.

**Comment by istr** [comment]
Closed. #1359 was merged and published in 1.1.0-beta4.
