### ISSUE TITLE
Create 1.1.0-beta4

### ISSUE THREAD

**Issue by istr** [n1k0/casperjs#1365]
Let's collect here what to include in 1.1-beta4 (my proposal: keep the list short).

I would propose to just edit this post, rather than adding comments, so we have a single top-level list.

  - [ ] n1k0/casperjs/issues/1260 (rationale: this seems to keep lots of people from sticking with CasperJS after the first attempt to install it, see https://github.com/n1k0/casperjs/pull/1315)
  - [ ] n1k0/casperjs/issues/532 (rationale: it should be pointed out that slimerjs is still **experimental** and that CLI support is not available yet at a prominent place)

**Comment by soulteary** [comment]
great! especial second issue.

and i have a question about sendKeys, current version is unfriendly to user who use the keycode,because it only support `string`

if i want to send `backspace` / `enter` / `end` / ....

and also if i want to press a key not on input[type=text] and textarea...

**Comment by shobhitg** [comment]
When are we planning for `1.1-beta4` milestone?

**Comment by istr** [comment]
Closing. Release 1.1.0-beta4 published, npm packages follow soon (see #1416).
