### ISSUE TITLE
CasperJS Doesn't output to stdout

### ISSUE THREAD

**Issue by optikalefx** [n1k0/casperjs#1366]
This is a really strange issue, but I've gotten the issue located down to casper. I have a PHP script that runs `shell_exec` which just runs a casper script.  But NULL is returned. If I run a phantomjs script, I get the output just fine.

However if I run that same casper script from terminal, it does output. So something in casper is swallowing the output.  PhantomJS outputs using console.log and phantom.exit. Casper never outputs to shell_exec.

CasperJS version 1.1.0-beta3 at /root/casperjs, using phantomjs version 1.9.8

**Comment by istr** [comment]
Please try to change the call to ```exec``` (http://php.net/manual/en/function.exec.php) and analyze / report the exit code of the call. With ```shell_exec``` you can't tell if the call to casper failed or did not produce output (http://php.net/manual/de/function.shell-exec.php).

Probably your call from PHP to CasperJS plainly fails (I would suspect issues with the ```PATH```).

This is a typical question that should be directed to [the mailing list first](http://groups.google.com/group/casperjs) because it might just be a problem with your specific PHP / CasperJS setup and not an issue with CasperJS itself.

**Comment by optikalefx** [comment]
For those coming here in the future. The solution ended up being to avoid using PHP to execute the call. So the setup for me is

- PHP app server >  
- cURL with information (not the actual request) to a server on the local network so the main server isn't doing the scraping. > 
- nodeJS which exec's a child process to run casper > 
- capserJS script > 
- which runs PhantomJS

**Comment by istr** [comment]
@optikalefx Thanks for reporting back.

There is a [related issue wanting to do the same](https://github.com/n1k0/casperjs/issues/1355).

It would be great if you could provide your node.js script that addresses your use-case so we could add it as an example.

**Comment by istr** [comment]
Ok, closing. Thanks for submitting your script. If you would like to go through the effort to create a ready-made example and create a PR that would be highly welcome. If you don't and we integrate an example based on your script we would mention your authorship and add a reference to your comment containing it.

**Comment by optikalefx** [comment]
@istr I would imagine it would be most helpful starting from node instead of mine which starts from PHP?

**Comment by soulteary** [comment]
hi, @optikalefx , you can use `system` and others cmd to excute casperjs ,eg: https://github.com/Pantimos/Dashboard.Pantimos/blob/master/eve-include/mock.class.php

**Comment by BIGjuevos** [comment]
I've created an example of how to create a web service with casper/phantomjs by blatantly stealing @mickaelandrieu's code and putting it into a [new section in the docs](http://docs.casperjs.org/en/latest/cookbook.html#creating-a-web-service).

**Comment by mickaelandrieu** [comment]
it's open source, you own this code, like everyone in universe ! ^o^
