### ISSUE TITLE
RPM for CasperJS 1.1-beta3

### ISSUE THREAD

**Issue by daniel-lucio** [n1k0/casperjs#1367]
http://inside-out.xyz/technology/rpm-for-casperjs-1-1-beta3.html

I have create RPMs following Centos6 and Centos7 guidelines.  Add this repo, then do yum install casperjs and it will install it with all deps.

Enjoy

**Comment by paazmaya** [comment]
Thank you!
Would you like to create a PR to add it in the documentation?

**Comment by daniel-lucio** [comment]
Yes, I will. Let me review where. I am not very good with git

**Comment by istr** [comment]
RPM build scripts are already in the repo: https://github.com/n1k0/casperjs/tree/master/rpm
@mickaelandrieu @n1k0 @paazmaya I am not sure if we want to start / keep publishing beta releases as rpm too.

Closing for the moment. Feel free to re-open when we have a maintainer for rpm and other packages.
