### ISSUE TITLE
Submitting form fails

### ISSUE THREAD

**Issue by Goudini** [n1k0/casperjs#1368]
I'm facing an issue when filling and submitting a form on CentOS.

[37;41;1mCasperError: Errors encountered while filling form: TypeError: 'undefined' is not a function (evaluating 'value.indexOf(option.value)')[0m
  /opt/casperjs/modules/casper.js:[33m805[0m in [36mfillForm[0m
  /opt/casperjs/modules/casper.js:[33m865[0m in [36mfillNames[0m
  /var/www/html/jpat/casperjs/praca3.pl.js:[33m93[0m
  /opt/casperjs/modules/casper.js:[33m1569[0m in [36mrunStep[0m
  /opt/casperjs/modules/casper.js:[33m397[0m in [36mcheckStep[0m

However on Windows works fine. What can be a reason?

**Comment by istr** [comment]
When asking for help, please ask your question [on the mailing list ](http://groups.google.com/group/casperjs) first.

If you feel that you need to report an issue against CasperJS (and you are sure that it is not a problem specific to your installation), please include at least:
- the platform you are running on (like here: CentOS)
- the CasperJS version you are using
- the engine type and version you are using
- a minimal example script and/or description of the specific situation that helps to *reproduce* your problem

Thank you.

(Feel free to re-open this issue if you come back with more specific information and asking on the mailing list did not lead to a solution)
