### ISSUE TITLE
capture page render wrong text (fonts issue)

### ISSUE THREAD

**Issue by soulteary** [n1k0/casperjs#1376]
hi, i'm trying to use casperjs captures the [website](https://www.baidu.com/), but all chinese chars show errors.

html code eg:

```
...
<input type="submit" id="su" value="百度一下" class="bg s_btn">
...
```

result page:

```
http://0.1.fox.pantimos.com/data/c4ca4238a0b923820dcc509a6f75849b/1450334604557/index.html
```

can i use casperjs with special font? 

Thank you.

**Comment by istr** [comment]
If it fails with the plain PhantomJS engine version you use, it fails in CasperJS, too.

Try using a different engine and/or engine version (current CasperJS master supports PhantomJS 1.9.1 through 2.0.0 and some SlimerJS versions experimental / without cli support).

Robust font-face / WebFont support is available as of PhantomJS 2.0.0 (this was the main reason for me to promote CasperJS support for 2.0.0).

**Comment by soulteary** [comment]
But i use PhantomJS v2.0.0(both OSX and Ubuntu) & Casperjs at latest...

/** I guess the problem is cause by the CJK font. **/

**Comment by istr** [comment]
Ok, seems you're out of luck... CasperJS can't fix such problems in the underlying engine(s).

If you have a look at what Chrome (linux) does, you will notice that:
- baidu uses ```arial```
- Chrome renders the missing glyphs using ```Droid Sans Fallback```

So if PhantomJS would support a similar fallback, it could work for you. Maybe you should try if SlimerJS supports a fallback out-of-the-box. The only workaround for you would be to hack in on the CSS and mimic the fallback using a webfont version of Droid Sans Fallback.

![droid-sans-fallback](https://cloud.githubusercontent.com/assets/4235579/11870178/910faef0-a4c5-11e5-88cc-829fdf64f6a2.png)

**Comment by soulteary** [comment]
@istr thank you for your reply , : )

**Comment by soulteary** [comment]
@istr there's a easy way to solve this problem:

just try to ```apt-get install fonts-droid``` on Ubuntu server.

And report it at https://github.com/ariya/phantomjs/issues/10249#issuecomment-166203957

Thank you.

**Comment by istr** [comment]
We should clearly document somewhere that PhantomJS might need external libs / fonts, even though they promote "static build" for binaries that are not really standalone:

```bash
ldd bin/phantomjs-1.9.6 
	linux-vdso.so.1 =>  (0x00007ffc5f9bb000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fbded3dd000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fbded1a0000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbdecf9c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fbdecd94000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbdecb75000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fbdec871000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbdec56b000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbdec354000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbdebf8f000)
	/lib64/ld-linux-x86-64.so.2 (0x0000562606dd9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbdebd76000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fbdebb4f000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fbdeb925000) 
```

There are some more issues connected to having a "not-so-very-static-binary" in PhantomJS.

**Comment by soulteary** [comment]
@istr You're right.
