### ISSUE TITLE
Need to forward --disk-cache-path option to PhantomJS

### ISSUE THREAD

**Issue by mepard** [n1k0/casperjs#1379]
--disk-cache-path is a new PhantomJS (>2.0) option to specify the location of
the disk cache. See https://github.com/ariya/phantomjs.

**Comment by mickaelandrieu** [comment]
Hi,

can you link at least to a documentation link or implementation ?

Thanks

**Comment by mepard** [comment]
The PhantomJS changes are at https://github.com/ariya/phantomjs/commit/c9e30ebafdeb42efe33900da7823142e146b0a1d

Just did a PR with the CasperJS changes.

--disk-cache-path=/path/to/cache/directory
