### ISSUE TITLE
each() or eachThen() don't work as expected

### ISSUE THREAD

**Issue by acegreen** [n1k0/casperjs#1381]
Hi guys,

Not sure if this is a bug or not but I'm trying to use each() or eachThen() to achieve a certain scenario. I have opened a gist here:
https://gist.github.com/acegreen/17a7e81630235d9012cd

With the help of a fellow coder I managed to get waitFor() somewhat going but the results are not as expect. Please take a look at the comments and let me know if its per design or am I missing something?

Thanks in advance,
Ace

**Comment by amerikan** [comment]
The gist link provide is broken.

**Comment by n1k0** [comment]
Please address support requests to the [Mailing-List](https://groups.google.com/forum/#!forum/casperjs). Thanks for your understanding.
