### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'phantomArgs.forEach')

### ISSUE THREAD

**Issue by sulthonzh** [n1k0/casperjs#1382]
Please help me, i have problem, i'm got error message 'TypeError: undefined is not an object (evaluating 'phantomArgs.forEach')'

**Comment by istr** [comment]
Please address your question to [the mailing list](https://groups.google.com/forum/#!forum/casperjs) and give at least CasperJS version, engine (PhantomJS, SlimerJS) and engine version when asking for help.

Seems you're using a [deprecated API](http://phantomjs.org/api/phantom/property/args.html). See also other projects having this problem, e.g. https://github.com/jamesgpearce/confess/issues/9, https://github.com/marcelduran/yslow/issues/129.
