### ISSUE TITLE
casperjs 1.1.0-beta3 installs perfectly, but simply doesn't load when require()d

### ISSUE THREAD

**Issue by mikemaccana** [n1k0/casperjs#1392]
casperjs 1.1.0-beta3 simply doesn't load via require:

    $ npm install --save casperjs
    npm WARN deprecated npmconf@2.1.1: this package has been reintegrated into npm and is now out of date with respect to npm

There are no other errors:

    $ node
    > require('casperjs')
    Error: Cannot find module 'casperjs'
        at Function.Module._resolveFilename (module.js:337:15)
        at Function.Module._load (module.js:287:25)
        at Module.require (module.js:366:17)
        at require (module.js:385:17)
        at repl:1:1
        at REPLServer.defaultEval (repl.js:251:27)
        at bound (domain.js:280:14)
        at REPLServer.runBound [as eval] (domain.js:293:12)
        at REPLServer.<anonymous> (repl.js:415:12)
        at emitOne (events.js:82:20)

    # grep version node_modules/casperjs/package.json
      "version": "1.1.0-beta3"

**Comment by mikemaccana** [comment]
Nevermind, the sentence doesn't make sense:

     While CasperJS is installable via npm, it’s not a NodeJS package, neither it’s capable to require native NodeJS modules.

Doesn't make sense in English.

     While CasperJS is installable via npm, it’s not a node.js package. **You cannot load casper by using `require()` in node**

**Comment by n1k0** [comment]
Yeah, sorry for being slightly too French. Could you please submit a PR with the suggested change? Thanks

**Comment by n1k0** [comment]
Thanks for the patch though could you please now send a PR? Thanks.

**Comment by mikemaccana** [comment]
Ooops I'd forgotten the PR. Done!
