### ISSUE TITLE
PhantomJS #10522: Function.prototype.bind() breaks when running under 'webserver' module (test case attached) 

### ISSUE THREAD

**Issue by mikemaccana** [n1k0/casperjs#1396]
Here's a minimal test case that will fail when run. It's using the common trick of making a short alias using Function.prototype.bind(), ie,:

    var log = console.log.bind(console)

Here's the test case:

	#!/usr/bin/env casperjs

	var casper = require('casper').create();
	var server = require('webserver').create();
	var ipAndPort = '127.0.0.1:8585';

	var log = console.log.bind(console)

	server.listen(ipAndPort, function(req, res) {

		casper.start('https://google.com');
		casper.then(function(){
			log('THIS LINE FAILS')
		});

		// This is somewhat misnamed: casper.run() starts the casper job, then runs the callback runs when complete
		casper.run(function(){
			res.close();
		});
	});
	log('CasperJS server running at http://'+ipAndPort+'/');

The `log('THIS LINE FAILS')` will fail with 

    TypeError: instanceof called on an object with an invalid prototype property

Note the object is a simple string, nothing special. It shouldn't have an invalid prototype.

**Comment by n1k0** [comment]
What does give 

```js
casper.echo('THIS LINE FAILS')
```

?

**Comment by istr** [comment]
Why do you use
```js
var log = console.log.bind(console);
```
instead of simply
```js
var log = console.log;
```
? The former creates a new function with ```this``` bound to console, while the latter keeps the call to console.log intact.

Could you demonstrate the bind problem with a function other than ```console.log``` and/or a different value bound to ```this```?

**Comment by n1k0** [comment]
The console object methods need to be bound to the console object when passed as a reference, otherwise it fails. This is most probably for security reasons. 

![](http://i.imgur.com/GQplnkM.png)

**Comment by istr** [comment]
Ok, @n1k0 thanks for explanation.

I verified the (modified) test case, it fails with phantomjs 1.9.6 and works with 2.0.0:

```sh
ENGINE_EXECUTABLE=~/bin/phantomjs-1.9.6 bin/casperjs bindconsole
CasperJS server running at http://127.0.0.1:8585/
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: https://google.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://google.com/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] Navigation requested: url=https://www.google.de/?gfe_rd=cr&ei=iPacVpbfC8eA8QeV2ZTIDg, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "https://www.google.de/?gfe_rd=cr&ei=iPacVpbfC8eA8QeV2ZTIDg"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step anonymous 3/3 https://www.google.de/?gfe_rd=cr&ei=iPacVpbfC8eA8QeV2ZTIDg (HTTP 200)
ECHO
CONSOLE
```

```sh
ENGINE_EXECUTABLE=~/bin/phantomjs-2.0.0 bin/casperjs bindconsole
CasperJS server running at http://127.0.0.1:8585/
[info] [phantom] Starting...
[info] [phantom] Running suite: 3 steps
[debug] [phantom] opening url: https://google.com/, HTTP GET
[debug] [phantom] Navigation requested: url=https://google.com/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] Navigation requested: url=https://www.google.de/?gfe_rd=cr&ei=IvecVpCaBYKh8wfAsZz4CQ, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "https://www.google.de/?gfe_rd=cr&ei=IvecVpCaBYKh8wfAsZz4CQ"
[debug] [phantom] Successfully injected Casper client-side utilities
[debug] [phantom] start page is loaded
[info] [phantom] Step anonymous 3/3 https://www.google.de/?gfe_rd=cr&ei=IvecVpCaBYKh8wfAsZz4CQ (HTTP 200)
ECHO
CONSOLE
THIS LINE FAILS
ECHO
ECHO
[info] [phantom] Step anonymous 3/3: done in 680ms.
[info] [phantom] Done 3 steps in 699ms
```

Test case used
```js
var casper = require('casper').create({
  verbose: true,
  logLevel: 'debug'
});
var server = require('webserver').create();
var ipAndPort = '127.0.0.1:8585';

var log = console.log.bind(console)

server.listen(ipAndPort, function(req, res) {

    casper.start('https://google.com');
    casper.then(function(){
        casper.echo('ECHO');
        console.log('CONSOLE');
        log('THIS LINE FAILS');
        casper.echo('ECHO');
        casper.echo('ECHO');
    });

    // This is somewhat misnamed: casper.run() starts the casper job, then runs the callback runs when complete
    casper.run(function() {
        res.statusCode = 200;
        res.write('OK');
        res.close();
    });
});
log('CasperJS server running at http://'+ipAndPort+'/');
```

**Comment by mikemaccana** [comment]
Thanks @istr!

**Comment by istr** [comment]
This is a well-known issue:
http://stackoverflow.com/questions/34046318/how-to-deal-with-console-log-bindconsole-throwing-error-in-phantomjs and it seems [that many people have tried to get grips on this with the best known workaround to use underscore.bind](https://github.com/ariya/phantomjs/issues/10522#issuecomment-35314457).

It seems, however that there is a slight chance fixing this in CasperJS, using a different [shim for bind in bootstrap.js](https://github.com/n1k0/casperjs/blob/master/bin/bootstrap.js#L45).

@mikemaccana Would be nice if you try out different shims there and come up with a PR if you succeed with a different shim.

**Comment by istr** [comment]
After a quick check it turns out that [the cujos polyfill mentioned here](https://github.com/ariya/phantomjs/issues/10522#issuecomment-39248521) solves the issue for me.

I will create a bugfix branch for that and a PR.

**Comment by istr** [comment]
PR created: https://github.com/n1k0/casperjs/pull/1404. Please check if this works for you.

**Comment by istr** [comment]
Ok, thanks for merging. Will reduce the test case for this issue and integrate it in the test suite in a second PR.

**Comment by mikemaccana** [comment]
Thanks @n1k0 and @istr. I'm about to try the cujo polyfill here now. Will Phantom 2 be default for Casper at some point in future?

**Comment by mikemaccana** [comment]
Hrm using the cujo polyfill from the PR doesn't seem to fix the test case. See below:

	var casper = require('casper').create({
		verbose: true,
		logLevel: 'debug'
	});
	var server = require('webserver').create();
	var ipAndPort = '127.0.0.1:8585';




	// cujos bind shim instead of MDN shim, see #1396
	var isFunction = function(o) {
		return 'function' === typeof o;
	};
	var bind;
	var slice = [].slice;
	var proto = Function.prototype;
	var featureMap = {
		'function-bind': 'bind'
	};
	function has(feature) {
		var prop = featureMap[feature];
		return isFunction(proto[prop]);
	}
	// check for missing features
	if (!has('function-bind')) {
		// adapted from Mozilla Developer Network example at
		// https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Function/bind
		bind = function bind(obj) {
			var args = slice.call(arguments, 1),
				self = this,
				nop = function() {
				},
				bound = function() {
					return self.apply(this instanceof nop ? this : (obj || {}), args.concat(slice.call(arguments)));
				};
			nop.prototype = this.prototype || {}; // Firefox cries sometimes if prototype is undefined
			bound.prototype = new nop();
			return bound;
		};
		proto.bind = bind;
	}





	var log = console.log.bind(console)

	server.listen(ipAndPort, function(req, res) {

		casper.start('https://google.com');
		casper.then(function(){
			casper.echo('ECHO');
			console.log('CONSOLE');
			log('THIS LINE FAILS');
			casper.echo('ECHO');
			casper.echo('ECHO');
		});

		// This is somewhat misnamed: casper.run() starts the casper job, then runs the callback runs when complete
		casper.run(function() {
			res.statusCode = 200;
			res.write('OK');
			res.close();
		});
	});
	log('CasperJS server running at http://'+ipAndPort+'/');

**Comment by istr** [comment]
@mikemaccana  No, this is not meant to be replicated in your test case, of course.

Just check out current master (the bugfix is merged) and try your original test case against it.

This works for me.

**Comment by mikemaccana** [comment]
@istr sorry, I should have mentioned: the test case above includes the cujo fix - that's why I pasted it. I'll try casper master tomorrow though...

**Comment by mikemaccana** [comment]
@istr Ah actually my test above only patched it if it wasn't already patched. I just tried installing master and running the original test: confirmed it's fixed now!!!
