### ISSUE TITLE
Unwait() does not work

### ISSUE THREAD

**Issue by maxbgn** [n1k0/casperjs#1397]
The Unwait() function does not work for me. The documentation says it should "Abort all current waiting processes, if any". But it does not. Here is an example:
```
var casper = require('casper').create();

casper.on("load.finished", function(err)
{
    this.echo("Calling casper.unwait");
    casper.unwait();
});

casper.start("http://google.com", function()
{
    this.wait(10000, function()
    {
        this.echo("I've waited for 10 seconds.");
    });
});

casper.run();
```
As you can see, the waiting continues all 10 seconds, even after casper.unwait call.

**Comment by justinklemm** [comment]
You may want to echo something directly above `wait(10000)` to see when it's being called in relation to the `unwait()`. I have a feeling that the callback for `casper.on("load.finished")` is being triggered *before* the callback for `casper.start("http://google.com")`. In other words, you may be calling `unwait()` before the `wait()` is called.

**Comment by maxbgn** [comment]
Omg, thank a lot man! For shame, for shame...
