### ISSUE TITLE
setTimeout is not executing in webpage code 

### ISSUE THREAD

**Issue by jasonlfunk** [n1k0/casperjs#1398]
I'm using `casperjs 1.1.0-beta3` using `phantoms 2.0.0`. I'm running through some browsers tests with logging enabled. The code looks like thing like this:

```
console.log('Before setTimeout');
window.setTimeout(function() {
    console.log('In setTimeout');
    ...
}.bind(this), 250);
```

When executing, the 'before setTimeout' message is printed but the 'In setTimeout' message doesn't appear. My casper test times out waiting for a selector to appear that is created in the `setTimeout` call. Why isn't the setTimeout call being executed?

**Comment by n1k0** [comment]
Please address support requests to the [Mailing-List](https://groups.google.com/forum/#!forum/casperjs). Thanks for your understanding.
