### ISSUE TITLE
It doesn't execute loaded JavaScripts when the script is quite large

### ISSUE THREAD

**Issue by unbornchikken** [n1k0/casperjs#1407]
I've written a detailed description [there](http://stackoverflow.com/questions/34904061/casperjs-doesnt-execute-javascript-code). In a nuthsell: I have a quite large JavaScript that gets loaded in a regular script tag. On Windows/OSX/PhantomJS it loads (I get HTTP 200) but the code doesn't get executed. By using SlimerJS/XUL the code works on Windows but on OSX it behaves exactly like with PhantomJS.

Does PhantomJS or SlimerJS have some platform specific limitations of script size/complexity? How one could overcome this limitation if exists?

**Comment by nathanboktae** [comment]
in the SO link it turns out you had a parse error.... is this still an issue? I don't think it is.

**Comment by unbornchikken** [comment]
The issue is turned out to be phantomjs' 2 lack of error feedback. I'll open it there, there is nothing needs to be done at cadsper side. Thanks, I'm closing this.
