### ISSUE TITLE
Phantomjs 2 released

### ISSUE THREAD

**Issue by josalmi** [n1k0/casperjs#1411]
Hi,

Phantomjs 2 has now been officially released. Which causes `npm install casperjs` to install newer version of phantomjs which isn't supported with the newest CasperJS release. Are you planning on updating CasperJS to a newer version sometime soon, or should we find long term workaround solutions to solve this issue.

```
$ npm install -g casperjs
\
> phantomjs@2.1.2 install /usr/local/lib/node_modules/casperjs/node_modules/phantomjs
> node install.js

PhantomJS not found on PATH
Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/yn/757l2f996mbgxz11tkbklm_80000gp/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [==========================--------------] 65%
```

**Comment by mickaelandrieu** [comment]
> Which causes npm install casperjs to install newer version of phantomjs which isn't supported with the newest CasperJS release.
Hi,
afaik the dev master of CasperJS works pretty well with PhantomJS 2.
Can you tell me the version of CasperJS installed through npm ?

@istr we probably need to make a new release like 1.1-beta4 

Regards,

**Comment by istr** [comment]
@mickaelandrieu 
> we probably need to make a new release like 1.1-beta4

... yes, in fact. See https://github.com/n1k0/casperjs/issues/1365

Maybe let us try to skip quickly through the two documentation issues I mentioned and create that. Will try hard to prepare things by end of week.

**Comment by istr** [comment]
[CasperJS 1.1.0-beta4 npm is published](https://www.npmjs.com/package/casperjs).
