### ISSUE TITLE
SlimerJs or not ?

### ISSUE THREAD

**Issue by seb2411** [n1k0/casperjs#1414]
Hello everyone !!

I'm creating some automatic testing with CasperJs, PhantomJs and SlimerJs.
I have no problem to use CasperJs with PhantomJs but it's different with SlimerJs.

First I have to run CasperJS with xvfb to be able to run SLimerJs in Headless mode.
I found this solution in some forum, but it could be useful to add the info in the documentation.

The second point is that I'm have no idea if I'm really running my test on Slimer (instead of PhantomJs). I don't have any variable or element I can check for it. If I dump via CasperJs cli I get this :

```
{
    "args": [
        "/casperjs/tests/"
        ],
        "options": {
        "casper-path": "/usr/local/lib/node_modules/casperjs",
        "cli": true
        },
        "raw": {
        "args": [
            "/casperjs/tests/"
            ],
            "options": {
            "casper-path": "/usr/local/lib/node_modules/casperjs",
            "cli": true
            }
            }
}

```
As I understand is missing the engine args/option

I'm launching my test with the following command using a python script:
```
os.system("xvfb-run -a casperjs \
    --engine=slimerjs \
    test /casperjs/tests/ \
")

```

Thx.

**Comment by mickaelandrieu** [comment]
Hi,

if you realy need this information, you can simply put an echo at start of your build:
```js
casper.echo(phantom.casperEngine);
```

**Comment by seb2411** [comment]
Thank you it's what I was looking for. ^^

**Comment by mickaelandrieu** [comment]
You're welcome ;) closed.
