### ISSUE TITLE
How to catch error in CasperJS script?

### ISSUE THREAD

**Issue by xpoft** [n1k0/casperjs#1423]
c.js:
```javascript
throw "Some exception 1";

var casper = require('casper').create();

throw "Some exception 2";

casper.run();
```

That's OK. We see it.
```
> casperjs c.js
> Some exception 1

  phantomjs://code/c.js:1 in global code
  :0 in injectJs
  phantomjs://code/bootstrap.js:427
```

But if we comment the first exception casperjs stops and we don't have any idea why.
```
> casperjs c.js
> 
```

How to see/log such type of errors?

**Comment by jefleponot** [comment]
Hi @xpoft ,

all is normal,

casper objet redefine the phantom.onError default method (casper.js line 1234).
So if you want to catch error just add
```
casper.on('error',function(msg, backtrace){
  console.log(msg);
});
```
after 
```
     var casper = require('casper').create();
```

**Comment by xpoft** [comment]
Thx

**Comment by istr** [comment]
...for more insight into what is going on, it could be a good idea to
```js
var casper = require('casper').create({
  verbose: true,
  logLevel: 'debug'
});
```
instead of 
```js
var casper = require('casper').create();
```

Please note that "issues" that qualify as "help request" belong to [the mailing list](https://groups.google.com/forum/#!forum/casperjs). Thank you.

**Comment by jefleponot** [comment]
@istr , I can't access to google groups
It is forbidden by my provider (my boss)
: :tongue: https://degooglisons-internet.org/

Is there any other forum access ?

**Comment by xpoft** [comment]
It doesn't help. You see nothing.

```
var casper = require('casper').create({
  verbose: true,
  logLevel: 'debug'
});
```

**Comment by istr** [comment]
> google groups
> It is forbidden by my provider (my boss)

@jefleponot Good point. We had other users (i.e. from China) unable to access the mailing list.

Maybe we should consider to move it ~Q2/2016.
