### ISSUE TITLE
casperjs.exe in beta4 prints phantomjs args before running

### ISSUE THREAD

**Issue by mepard** [n1k0/casperjs#1426]
This causes clitests to fail. It just needs to be recompiled. (It needs to be recompiled for the next downloadable version anyway to incorporate #1389).

```
C:\Users\Marc\Downloads\n1k0-casperjs-1.1-beta4-0-g3aa6f76\n1k0-casperjs-3aa6f76>casperjs.exe --version
"C:\Users\Marc\Downloads\n1k0-casperjs-1.1-beta4-0-g3aa6f76\n1k0-casperjs-3aa6f76\bin\bootstrap.js" --casper-path="C:\Users\Marc\Downloads\n1k0-casperjs-1.1-beta4-0-g3aa6f76\n1k0-casperjs-3aa6f76" --cli --version
1.1.0-beta4
```

If I recompile it, it stops printing the args:

```
C:\Users\Marc\Downloads\n1k0-casperjs-1.1-beta4-0-g3aa6f76\n1k0-casperjs-3aa6f76>csc.exe /out:bin\casperjs.exe src\casperjs.cs
Microsoft (R) Visual C# Compiler version 12.0.40629.0
for C# 5
Copyright (C) Microsoft Corporation. All rights reserved.


C:\Users\Marc\Downloads\n1k0-casperjs-1.1-beta4-0-g3aa6f76\n1k0-casperjs-3aa6f76>casperjs.exe --version
1.1.0-beta4
```

**Comment by istr** [comment]
Ah, very good point. This will be fixed ASAP.

**Comment by mickaelandrieu** [comment]
we only need to compile casperjs.cs and bump the new casperjs.exe in `bin` folder right ?

could be nice to tag a new 1.1-beta4.1 only for this change, what do you think @istr ?

**Comment by mepard** [comment]
Rignt.

**Comment by istr** [comment]
I guess it would be better to package / publish -beta5 including #1389 right away. I could do this tomorrow morning.

Seems cleaner to me.

**Comment by istr** [comment]
@mepard Could you please check if https://github.com/istr/casperjs/tree/hotfix/windows-binary works for you (OS/X mono and/or linux mono test ```make selftest-dotNET```)? Thank you.

**Comment by mepard** [comment]
It works on OS X. It also works on Windows 10, but gets the failures in #1427.

**Comment by istr** [comment]
Closing. 1.1-beta5 is out as npm, too.
