### ISSUE TITLE
does nativescript support casperjs??

### ISSUE THREAD

**Issue by jjTudu** [n1k0/casperjs#1428]
i am trying to use casperjs in nativescript Application, through the require method of nativescript,
var casp=require("casperjs");
Error occurs every time, if i comment it out application execute perfectly.
If it does support, please someone tell me the proper way to do it.

**Comment by istr** [comment]
Probably [this problem](http://docs.casperjs.org/en/latest/faq.html#faq-test-casper-instance). Please address basic support questions to [the mailing list](https://groups.google.com/forum/#!forum/casperjs).
