### ISSUE TITLE
`page.render` overwritten in `casper.each`

### ISSUE THREAD

**Issue by sircelsius** [n1k0/casperjs#1443]
As part of a larger application, I want to run something like the following:

``` javascript
casper.each(['google', 'yahoo'], function(self, url){
  self.test.begin(url, function(test) {
    self.test.on('fail', function() {
      self.page.render(url + '.png');
    });

    self.start('http://www.' + url + '.com', function() {});

    self.then(function() {
      test.assert(false);
    })

    self.run(function() {
      test.done();
    })
  })
})
```

Where I test a series of pages by `casper.each` on a an input array.

Every time a test fails, I want to render the corresponding page as a PNG file for a secondary manual test.

However the above code has the following behaviour:

  * fail on `http://www.google.com` -> render a screenshot of the Google home page in `./google.png`
  * fail on `http://www.yahoo.com` -> render a screenshot of the **Yahoo home page in `./google.png`** and a screenshot of the Yahoo home page in `./yahoo.png`.

In the past (`1.1-beta3`, I haven't tested `1.1-beta4`), I could hack around this issue by adding the following to my `on('fail')` callback:

``` javascript
if(failure.suite === url) {
  // render screenshot
}
```

But it seems that `1.1-beta4` removed `suite` from the failure event.

**Is this intended? Is there another workaround to take not overwrite the previous screenshots in the `on('fail')` callback?**

**Note** I did try to do something with `setUp` and `teardown`, it doesn't seem to do the trick.

**Comment by istr** [comment]
The problematic pattern is that you bind to the event ```'fail'``` in the loop but fail to remove the previous handler(s), so they accumulate. If you add a third URL to the loop, e.g. "example", the handler would be called three times on fail.

You need to memorize your listener function in the context of your ```each``` loop and then ```casper.removeListener('fail', listener)``` before adding a new listener (best move the prototype of the listener function out of the loop and ```listener.bind(this, url)``` to create a new listener instance in the loop).

See http://docs.casperjs.org/en/latest/events-filters.html#removing-events

**Comment by sircelsius** [comment]
I'll try this, thanks.
