### ISSUE TITLE
issue: casperjs through proxy

### ISSUE THREAD

**Issue by zeepi222** [n1k0/casperjs#1445]
Hello,

I am having issues using casperjs through a BlueCoat ProxySG (NTLM) proxy.

Casper version: 1.1.0-beta5
Phantom version: 2.1.1

When I use casper with the "--proxy-auth=userx:passx" then my script works without issue. This is not suitable however as our system admins have complained that they don't want to see proxy credentials being displayed in the command line history. I therefore am trying to move the proxy auth settings from the command line into the script.

I have tried these approaches in caperjs without any luck;
```

var casper = require('casper').create({
  pageSettings: {
    userName: 'userx',
    password: 'passx'
  }
});

casper.setHttpAuth('userx', 'passx');

casper.setProxy('10.48.2.254','8080','manual','userx','passx');

casper.customHeaders={'Authorization': 'Basic '+btoa('userx:'passx')};
```

I tested the following directive with phantomjs and it is working successfully;

`phantom.setProxy('10.48.2.254','8080','manual','userx','passx');`

I am not sure if this is a bug, as it works with phantomjs but I am unable to get it working with casperjs ?

Thanks in advance.

**Comment by mickaelandrieu** [comment]
Hi,

there is the list of options available in phantomjs that casperjs is able to set: https://github.com/n1k0/casperjs/blob/master/bin/casperjs#L15

I didn't have tested, but this sample should works:

```js
var casper = require('casper').create({
    proxy: "127.0.0.1:1234",
    proxy-auth: "userx:passx",
    proxy-type: "meh"
});
/* ... */
```

Mickaël

PS: Happy scrapping !

**Comment by zeepi222** [comment]
Awesome, thanks Mickaël
Let me try this and post back with my findings.

**Comment by zeepi222** [comment]
No luck unfortunately. It doesn't appear to like the hyphen between proxy and auth ,,,

SyntaxError: Unexpected token '-'

  phantomjs://code/ctest.js:4 in injectJs
  phantomjs://code/bootstrap.js:427

**Comment by istr** [comment]
> No luck unfortunately. It doesn't appear to like the hyphen between proxy and auth ,,,

```proxy-auth``` cannot work that way. Try:

```js
var casper = require('casper').create({
    proxy: "127.0.0.1:1234",
    "proxy-auth": "userx:passx",
    "proxy-type": "meh"
});
/* ... */
```

**Comment by mickaelandrieu** [comment]
:+1: yes, sorry for that !

**Comment by zeepi222** [comment]
Thanks for trying to help guys, but not having much luck here ...

Here is the updated script;
```
// Driver options
var casper = require('casper').create({
  proxy: "10.22.1.1:8080",
  "proxy-auth": "userx:passwdx",
  "proxy-type": "manual"
});

// XPATH variables
var xpath = require('casper').selectXPath;
var login_button = xpath('//*[@id="loginForm_login"]');

var url = 'https://dev.cloud9.net/'

casper.start(url, function() {
    this.waitForSelector(login_button, function () {
        this.echo('Login button loaded');
    });
});

casper.run();

```
If I run the script without the command line arguments, it fails with "[warning] [phantom] Loading resource failed with status=fail" 
```
[root@dext01 scripts]# casperjs --verbose --log-level=debug ctest.js
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: https://dev.cloud9.net/, HTTP GET
[debug] [phantom] Navigation requested: url=https://dev.cloud9.net/, type=Other, willNavigate=true, isMainFrame=true
[warning] [phantom] Loading resource failed with status=fail: https://dev.cloud9.net/
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 2/2: done in 2626ms.
[info] [phantom] Step _step 3/3: done in 2646ms.
[warning] [phantom] Casper.waitFor() timeout
[error] [phantom] Wait timeout of 5000ms expired, exiting.
Wait timeout of 5000ms expired, exiting.
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"

```
The script is successful if I use command line arguments.
```
[root@dext01 scripts]# casperjs --verbose --log-level=debug --proxy=10.22.1.1:8080 --proxy-auth=userx:passwdx ctest.js
[info] [phantom] Starting...
[info] [phantom] Running suite: 2 steps
[debug] [phantom] opening url: https://dev.cloud9.net/, HTTP GET
[debug] [phantom] Navigation requested: url=https://dev.cloud9.net/, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "https://dev.cloud9.net/"
[debug] [phantom] Successfully injected Casper client-side utilities
[info] [phantom] Step anonymous 2/2 https://dev.cloud9.net/ (HTTP 200)
[info] [phantom] Step anonymous 2/2: done in 1375ms.
[info] [phantom] Step _step 3/3 https://dev.cloud9.net/ (HTTP 200)
[info] [phantom] Step _step 3/3: done in 1396ms.
[info] [phantom] waitFor() finished in 40ms.
[info] [phantom] Step anonymous 4/4 https://dev.cloud9.net/ (HTTP 200)
Login button loaded
[info] [phantom] Step anonymous 4/4: done in 1456ms.
[info] [phantom] Done 4 steps in 1475ms
[debug] [phantom] Navigation requested: url=about:blank, type=Other, willNavigate=true, isMainFrame=true
[debug] [phantom] url changed to "about:blank"
[root@dext01 scripts]# 
```

**Comment by mickaelandrieu** [comment]
humm,

phantomjs has a [setProxy() function](https://github.com/ariya/phantomjs/pull/11829/files).

We may add a new function in casper module, right ? 

Mickaël

**Comment by istr** [comment]
> We may add a new function in casper module, right ?

Good idea -- did you check the first version supporting it? How about SlimerJS support?

**Comment by mickaelandrieu** [comment]
@istr actual slimerjs docs dont mention this feature. I'm not sure about the first version of phantomjs, cause this is still undocumented => https://github.com/ariya/phantomjs/commit/9da842df2b5ad6aa8e36166bd55f8f14aa928d8d

For now, we can directly call phantomjs.setProxy() in casperjs script without add this function as phantom object is global in casperjs context.

ping @laurentj

**Comment by zeepi222** [comment]
Will I be able to set "phantomjs.setProxy()" in the casperjs script now or do I need to wait for a patch / code update?

**Comment by mickaelandrieu** [comment]
@zeepi222 if you use phantomjs 2+ this "should"  work

**Comment by zeepi222** [comment]
@mickaelandrieu 

I am using ...
Casper version: 1.1.0-beta5
Phantom version: 2.1.1

Any clues how the implementation should look?

```
// Driver options
var casper = require('casper').create({
  phantom.setProxy('10.48.2.254','8080','manual','userx','passx')
});
```

or

```
// Driver options
var casper = require('casper').create({
  "phantom.setProxy" = ('10.48.2.254','8080','manual','userx','passx')
});
```

**Comment by zeepi222** [comment]
OK, this implementation worked :)

```
// Driver options
var casper = require('casper').create({
});
phantom.setProxy('10.48.2.254','8080','manual','userx','passx');

```

Thank you for your assistance with this issue @mickaelandrieu and @istr

**Comment by istr** [comment]
Closing. @mickaelandrieu do we want to create a separate issue for the possible ```setProxy()``` enhancement?

**Comment by mickaelandrieu** [comment]
@istr we don't need to complete the API because phantomjs is available. More,  it's a very specific need and we already address proxy configuration through cli args.
