### ISSUE TITLE
casperjs selftest fails for me

### ISSUE THREAD

**Issue by Verkeersregeling** [n1k0/casperjs#1450]
I just started to have a look at casperjs and tried the selftest.
I downlaoded phantomjs-2.1.1-windows and n1k0-casperjs-1.0.3-0-g76fc831

After initially running into endless loops I eventually I was left with 20 errors/failures.
(more details on the looping errors below)

I run the test in a cmd window with 
@echo off
set "orgpath=%path%"
set "path=%orgpath%;D:\utest\testsuite\phantomjs\bin;D:\utest\testsuite\casperjs\bin;D:\utest\testsuite\casperjs\batchbin"
casperjs selftest
set "path=%orgpath%"
pause

I needed the " in the set options because MySQL has an & inside the original path variable.

result:
FAIL 679 tests executed in 32.122s, 659 passed, 20 failed.

Details for the 20 failed tests:

In D:/utest/testsuite/casperjs/tests/suites/http_status.js:0
   assertHttpStatus: file:// protocol does not set a HTTP status
In D:/utest/testsuite/casperjs/tests/suites/require.js:0
   fail: require() patched version can load a js module
In D:/utest/testsuite/casperjs/tests/suites/require.js:0
   fail: require() patched version can load a coffeescript module
In D:/utest/testsuite/casperjs/tests/suites/require.js:0
   fail: require() patched version can load a json module
In D:/utest/testsuite/casperjs/tests/suites/t/encode.js:0
   assertEquals: Casper.base64encode() can retrieve base64 contents
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertEvalEquals: Casper.fill() can select a file to upload
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertEquals: Casper.getFormValues() retrieves filled values
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() input[type=email] field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() input[type=password] field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() textarea field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() input[type=checkbox] field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() input[type=radio] field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertUrlMatch: Casper.fill() select field was submitted
In D:/utest/testsuite/casperjs/tests/suites/t/formfill.js:0
   assertEquals: Casper.getFormValues() correctly retrieves values from radio inputs regardless of order
In D:/utest/testsuite/casperjs/tests/suites/t/logging.js:0
   assertEquals: Casper.log() logged messages
In D:/utest/testsuite/casperjs/tests/suites/tester.js:0
   assertEquals: findTestFiles() find test files and sort them
In D:/utest/testsuite/casperjs/tests/suites/tester.js:0
   assertField: Tester.assertField() works as expected with file inputs
In D:/utest/testsuite/casperjs/tests/suites/tester.js:0
   assertField: Tester.assertField() works as expected with selects
In D:/utest/testsuite/casperjs/tests/suites/utils.js:0
   assertEquals: betterTypeOf() detects expected type "[object Window]"
In D:/utest/testsuite/casperjs/tests/suites/utils.js:0
   assertEquals: isValidSelector() checks for a valid selector

But I only managed to get that far after removing/renaming a number of files.

coffee.coffee
I get a repeating error
FAIL SyntaxError: Unexpected token '>'
#    type: uncaughtError
#    error: "SyntaxError: Unexpected token '>'"
solution: rename to coffee.coffee.xxx

resources.coffee
I get a repeating error
FAIL SyntaxError: Unexpected string "tests/site/resources.html"
#    type: uncaughtError
#    error: "SyntaxError: Unexpected string \"tests/site/resources.html\""
solution: rename to resources.coffee.xxx

flow.coffee
I get a repeating error
FAIL SyntaxError: Invalid character: '#'
#    type: uncaughtError
#    error: "SyntaxError: Invalid character: '#'"
solution: rename to flow.coffee.xxx

headers.js
I get a repeating error
FAIL TypeError: Requested keys of a value that is not an object.
#    type: uncaughtError
#    error: "TypeError: Requested keys of a value that is not an object."
solution: rename to headers.js.xxx

Now I guess I'm missing something to enable coffeescript on my PC, but that leaves the last error in the headers.js. Eventually the errors are resulting in a repeating error D:/utest:170 mixed with D:/utest:179
My cmd file is located in the D:/utest/ folder.

I'm running on a Windows 10 computer.

Any help would be welcome.
Ferry van den Heuvel

**Comment by istr** [comment]
> I downlaoded phantomjs-2.1.1-windows and n1k0-casperjs-1.0.3-0-g76fc831

This won't work. PhantomJS 2 support is available as of https://github.com/n1k0/casperjs/releases/tag/1.1-beta4.

Please use the latest beta (or master git) when trying to run CasperJS with PhantomJS 2.

There are some selftests known to fail in windows, see #1427.

**Comment by Verkeersregeling** [comment]
Thank you. That version works much better, resulting in only the three known fails.
