### ISSUE TITLE
Encoded urls fail when using phantomjs 2.2.1

### ISSUE THREAD

**Issue by mepard** [n1k0/casperjs#1464]
If the first url(s) opened requires encoding, the response lacks the status. After a url is opened that does not require encoding, urls that require encoding work okay. In the following sequence, url 1 fails, url 2 works, url 3 works:

    page%20_1.html
    page_2.html
    page%20_3.html

In this sequence, all work okay:

    page_1.html
    page%20_2.html
    page%20_3.html

Stay tuned for a PR with a test that demonstrates the problem.

**Comment by mepard** [comment]
Looks like this only happens with phantomjs 2.2.1.

**Comment by mepard** [comment]
It turns out the "success" when changing the url order was not real. The encoded url gets derailed in Casper.prototype.handleReceivedResource on the line

    if (utils.decodeUrl(resource.url) !== this.requestUrl)  

The page.resource.received event does't get emitted and casper.currentResponse doesn't get updated.

**Comment by mhenry1384** [comment]
URLs with percent signs work fine in phantomjs, so it's a bug in casper.  
"http://www.google.com?h%20y" will fail in casper.

Otherwise, casper is an amazing tool.  :-)

**Comment by mickaelandrieu** [comment]
@mhenry1384 can you make a pull request with a test that highlight this issue ?

**Comment by mepard** [comment]
@mickaelandrieu It's in #1465 along with fix.
