### ISSUE TITLE
how to print error log

### ISSUE THREAD

**Issue by Awakening-j** [n1k0/casperjs#1466]
how to config to print casper error log, nothing print but finished program. I've set `logLevel: "error"`
![2016-03-03 13 50 07](https://cloud.githubusercontent.com/assets/8085088/13485879/e88698ac-e146-11e5-9d02-0db12bded022.png)

**Comment by ket4yii** [comment]
You need to add event listener for error event in your code and print errors manually(it is because, I think, phantomjs intercept internal errors and doesn't print it in standard out).

Example that could help you:
```
casper.on('error', function (err) {
  this.log(err, 'error');
  this.exit(1);
});
```

And some advice: you can use JSLint/JSHint to avoid this situation.

**Comment by Awakening-j** [comment]
thanks
