### ISSUE TITLE
Newbee: Cant get CoffeeScript to work

### ISSUE THREAD

**Issue by softwarerero** [n1k0/casperjs#1469]
I have casperjs 1.0.4 installed, CoffeeScript is 1.10.0. `casperjs googlelinks.js` runs fine, but `casperjs googlelinks.coffee` returns 
```
SyntaxError: Unexpected token '>'

  phantomjs://code/googlelinks.coffee:4 in injectJs
  phantomjs://code/bootstrap.js:427
```

Is this a bug or am I missing something?

**Comment by hexid** [comment]
What version of PhantomJS are you using?

PhantomJS v2.x no longer supports CoffeeScript.

**Comment by softwarerero** [comment]
I'm using 2.1.1, so I downgrade to 1.9.x.

**Comment by softwarerero** [comment]
It works with PhantomJS 1.9.7.
