### ISSUE TITLE
Warn when using CoffeeScript in PhantomJS v2.x

### ISSUE THREAD

**Issue by hexid** [n1k0/casperjs#1470]
We should probably give a warning if we detect CoffeeScript being used when it isn't supported (eg Phantom v2.x)

I'll try to put together a PR for this over the weekend.

ref #1469

**Comment by istr** [comment]
Yes, a warning would be great.

**Comment by mickaelandrieu** [comment]
:+1: how about CasperJS 1.0.5 with warnings and maybe some bug fixes?  We should announce also the end of maintenance for this branch.

**Comment by chrismetcalf** [comment]
An update to the docs to state this would be nice too, I just burned an hour or so trying to figure out why my CoffeeScript test script was hanging.

**Comment by istr** [comment]
> CasperJS 1.0.5 with warnings and maybe some bug fixes? We should announce also the end of maintenance for this branch.

I would tend to say "with warnings and end of maintenance announcement". PhantomJS will not backport bug fixes to 1.9.x versions, so I don't see any good reason for (very late) bug fixes in an obsolete version.

**Comment by entrptaher** [comment]
Whatever you guys say, http://docs.casperjs.org/en/latest/quickstart.html#quickstart still says you can use **Coffeescript**. It's misleading people.

**Comment by chrismetcalf** [comment]
Yep, that's the trap I fell into. Converted some perfectly good tests from
JS to CoffeeScript and then got stuck for an hour or two.

**Comment by mickaelandrieu** [comment]
Hmm, we will add [a notice](https://github.com/n1k0/casperjs/pull/1498) for sure, but it's up to you to know your tools: it's phantomjs 2 that does'nt support Coffeescript anymore, and CasperJS is *only* a wrapper around PhantomJS or SlimerJS.

**Comment by istr** [comment]
@entrptaher, @chrismetcalf Hopefully this will be addressed in #1498 very soon. If you want to speed things up, replace with your own PR. Thank you.

**Comment by istr** [comment]
Closing, because we merged #1498 and updated the public documentation: http://docs.casperjs.org/en/latest/quickstart.html#quickstart

@entrptaher, @chrismetcalf Please check if this improves the situation. Thank you.
