### ISSUE TITLE
Persistent Cookies Question - If I run Casper again?

### ISSUE THREAD

**Issue by LuckyLillia** [n1k0/casperjs#1473]
For example, in my code I login to a forum using my credentials.
If I exit casper, and after sometime, I want to run again,
Then I again get the login screen.

But if I login from my browser, it stores the cookie, right?

Similarly in casper can I use the previous login cookies and try to directly go to the home page?

How to do this?

**Comment by robin-obrien** [comment]
When you run the program add a command line argument "--cookies-file=cookiejar.json"

**Comment by LuckyLillia** [comment]
The file is not being saved. Also, how to I access the cookie file?

**Comment by robin-obrien** [comment]
Can you write the command line argument you wrote? Which OS are you using?

**Comment by LuckyLillia** [comment]
Got it right when I used this code:

Saving cookies:

var fs = require('fs');
var cookies = JSON.stringify(phantom.cookies);
fs.write(cookiejar, cookies);

For restoring cookies:

var fs = require('fs');
var data = fs.read(cookiejar);
phantom.cookies = JSON.parse(data);
