### ISSUE TITLE
Data driven testing using casperjs

### ISSUE THREAD

**Issue by Prateek032** [n1k0/casperjs#1476]
Is there any plan in pipeline to support data driven frame work using casperjs? It will be very helpful to automate things

**Comment by istr** [comment]
I don't think so. You might want to try https://github.com/fluentsoftware/data-driven in combination with https://github.com/nathanboktae/mocha-casperjs.

**Comment by Prateek032** [comment]
thanks @istr . But it will be very helpful, if casper provides data driven option
