### ISSUE TITLE
Adding extension as native Casperjs function

### ISSUE THREAD

**Issue by entrptaher** [n1k0/casperjs#1500]
This repo has .label() and .goto() extension for casperjs. 
https://github.com/yotsumoto/casperjs-goto

When you code a macro/testing script, sometimes you face situations where you have to go back to x step if a condition didn't match. i.e,

```
Go to google.com,
Click about,
If has text "I'm feeling lucky" click it,
else go back to **1st** step.
```

No I am not talking about repeat() function. I am talking about where you can jump through steps at your will. Just like how we use goto in a batch/shell file. Surely you can bypass() steps, but what about going nth step backward?

Is there any hope of these extensions to become part of original CasperJS repo?

NOTE: the first casperjs issue was about this too. No solution even after this many years?
https://github.com/n1k0/casperjs/issues/1

**Comment by mickaelandrieu** [comment]
Nope,  but we encourage anyone to make and share good extensions as described in documentation. 

Thank you for your feedback @entrptaher

**Comment by entrptaher** [comment]
Well, it was easier than it looked like. But I wonder if I should do a pull request or fork it. 
For now, I think I'll fork it.

I added this code below the block **Casper.prototype.zoom** in the casper.js module.
And it works.

```javascript
// Extending Casper functions for realizing label() and goto()
/**
 * Adds a new navigation step by 'then()' with naming label
 *
 * @param String labelname Label name for naming execution step
 */
Casper.prototype.label = function label(labelname) {
    var step = new Function('"empty function for label: ' + labelname + ' "'); // make empty step
    step.label = labelname; // Adds new property 'label' to the step for label naming
    this.then(step); // Adds new step by then()
    return this;
};

/**
 * Goto labeled navigation step
 *
 * @param String labelname Label name for jumping navigation step
 */
Casper.prototype.goto = function goto(labelname) {
    for (var i = 0; i < this.steps.length; i++) { // Search for label in steps array
        if (this.steps[i].label == labelname) { // found?
            this.step = i; // new step pointer is set
        }
    }
    return this;
};
// End of Extending Casper functions for realizing label() and goto()
```

Example code to run:
```javascript
var casper = require('casper').create();
casper.start();

casper.label("STEP1");
casper.then(function () {
    this.echo("This is step 1");
    this.goto("EOF");
});

casper.label("STEP2");
casper.then(function () {
    this.echo("This is step 2");
    this.goto("EOF");
});

casper.label("EOF");
casper.then(function () {
    this.echo("This is EOF");
});

casper.run( function() {
  this.dumpSteps( true );
  this.exit();
});
```

And it should go to step 1 and then jump to eof.
And do **do..while ** loops too when asked.

Who knows, someone might give it a shot. :)

**Comment by istr** [comment]
@entrptaher The step from a fork to a PR is short. If you have a full change set (implementation + test + documentation) a PR would be highly welcome.

**Comment by jefleponot** [comment]
Excellent idea @entrptaher :+1: 
Could you propose a PR ? 

I don't like "GOTO" for a method name. it has a very bad signification in computing (in French we name it "spaghetti code" because of crazy loop)
It may be better to reuse "bypass" method 

>   bypass()

>   Signature: bypass(Number nb | String Label)

**Comment by istr** [comment]
> I don't like "GOTO" for a method name. it has a very bad signification in computing

Indeed, but this is exactly what this ```goto``` function achieves -- with all the negative connotation attached to that behavior, so I deem this name appropriate. It is like a big fat **caveat emptor** so I would stick with it here.

**Comment by jefleponot** [comment]
I disagree with you @istr. @entrptaher's example use the goto method as a bypass.

here is a real GOTO call :

````
var casper = require('casper').create();
var loop = 10;
casper.start();

casper.label("STEP1");
casper.then(function () {
    this.echo("This is step 1");
    if (loop-- > 0) {
        this.goto("STEP3");
    } else {
        casper.exit(0);
    }
});

casper.label("STEP2");
casper.then(function () {
    this.echo("This is step 2");
    this.goto("STEP1");
});

casper.label("STEP3");
casper.then(function () {
    this.echo("This is STEP3");
    this.goto("STEP2");
});

casper.run( function() {
  this.dumpSteps( true );
  this.exit();
});
```

**Comment by jefleponot** [comment]
@entrptaher , how do you have colour on you code :-) ?

**Comment by istr** [comment]
@jefleponot 
> here is a real GOTO call :

My point is that you are able to produce the example you give with the functionality proposed. IMHO naming is not about how you are *supposed to use* something (a function) but what something (the function) *really does*. In this case the function provides a plain, old ```goto``` with all the broken code you might produce using it, hence the name is appropriate.

To colorize code examples, indicate the language you use after the three ticks, e.g. 
```
```js
...
```

see https://guides.github.com/features/mastering-markdown/#examples

**Comment by jefleponot** [comment]
thank to you @istr  :smile: 

Instead that : 
````js
/**
 * Goto labeled navigation step
 *
 * @param String labelname Label name for jumping navigation step
 */
Casper.prototype.goto = function goto(labelname) {
    for (var i = 0; i < this.steps.length; i++) { // Search for label in steps array
        if (this.steps[i].label == labelname) { // found?
            this.step = i; // new step pointer is set
        }
    }
    return this;
};
// End of Extending Casper functions for realizing label() and goto()
````
it could be better this : 

````js
/**
 * Bypasses `nb` steps or go to label.
 *
 * @param  mixed  nbOrLabel  Number of steps to bypass or String Label name for jumping navigation step 
 */
Casper.prototype.bypass = function bypass(nbOrLabel) {
    "use strict";
    var step = this.step,
        steps = this.steps,
        last = steps.length;
    this.checkStarted();
    if (utils.isNumber(nbOrLabel))
        this.step = Math.min(step + nbOrLabel, last);
    } else {
        for (var i = step, l = this.steps.length; i <l ; i++) { // Search for label in steps array
            if (this.steps[i].label == nbOrLabel) { // found?
                this.step = i; // new step pointer is set
            }
        }
    }
    this.emit('step.bypassed', this.step, step);
    return this;
};


````

**Comment by istr** [comment]
@jefleponot I object.

What you propose is an implicit variant of [the boolean trap](http://ariya.ofilabs.com/2011/08/hall-of-api-shame-boolean-trap.html). The "red flag" here is the change of the signature from ```Number``` to ```Mixed```. It complicates and potentially breaks the existing API:
- a single function is used to achieve different functionality
  1.   skip ```n``` steps
  2.   jump to step with ```label```
- the "boolean" trap is made implicit here and the function switches behavior based on the type of the argument passed in

Not a good API design IMHO. Keeping ```bypass``` and ```goto``` separate and make them do what their name indicates is a better choice. And it is much better with regards to BC. Keeping them separate you could just say "```goto``` introduced in rev. x.y.z" instead of "```bypass``` behavior changed as of x.y.z". Just my 2 cents.

**Comment by jefleponot** [comment]
you convinced me @Istr, thank you for your explanations.

**Comment by entrptaher** [comment]
@istr, The step from a fork to a PR is really short, but the documentation, test etc etc is the problem, so I asked if anyone is interested or not :D . Then we can enhance it even more.

I was looking for it, but then found someone else already built it. I feel the need of these inside original casperjs :3 . A typical behavior of an enhancement if you ask me.

@jefleponot, you see, I can just use negetive bypass like bypass(-1) etc etc. But keeping track of all these steps would be just a pain. Labeling them and using them however I like is what I wanted to do.

There are more to it. Something like opening newtab and having labeled steps inside that newtab, or just like the repo, a dumpstep() function. 

Lets see how it goes :) . Rushing things will only hurt.

**Comment by jefleponot** [comment]
hi @entrptaher , @istr 

It could also be nice to directly use the "Function" property : Function.name 

````javascript
var casper = require('casper').create();
casper.start();

// lets suppose This is Step 0
casper.then(function STEP1() {
    this.goto("EOF");
});

...

// lets suppose This is last step
casper.then(function EOT() {
    this.echo("This is EOF");
});

casper.run( function() {
  this.exit();
});

````


with 

````javascript
/**
 * Goto labeled navigation step
 *
 * @param String labelname Label name for jumping navigation step
 */
Casper.prototype.goto = function goto(labelname) {
    for (var i = 0; i < this.steps.length; i++) { // Search for label in steps array
        if (this.steps[i].label === labelname || this.steps[i].name === labelname) { // found?
            this.step = i; // new step pointer is set
        }
    }
    return this;
};
// End of Extending Casper functions for realizing label() and goto()
````

**Comment by BIGjuevos** [comment]
Perhaps I just don't understand the use case fully, but this feels like we are leaning on desired functionality rather than re-writing some existing code to be able to operate conditionally.  This doesn't pass my smell test.

This feels like something we could solve with abstraction and conditionals.  Or even test generation.  Let alone the potential for abuse of this functionality, and the high risk it has to introduce bugs by doing synchronous things in an asynchronous language.

Not trying to be harsh.  Perhaps you could give an example you've encountered that could only be solved with goto and not abstraction or test generation.

**Comment by entrptaher** [comment]
Say, we have a dynamic page that shows different output depending on user action. No matter which one we follow, it will end up to a page 2. Page 2 is same for all those dynamic outputs. But it doesn't stop here, we have a page 3 which leads to page 1 or page 4 depending on users action.

Say, you create a project that uses this conditional operation for 20 different pages, always going back and forth depending on the users behavior. What would you do? Just rewrite "some code"? 

If you say using bypass. Well, if you just add a little .then() inside the code, you have to give a different target for .bypass() function.

We can bypass the steps forward, but going backwards is a problem. We can use a function with some if else condition. But...we'll be less productive. Of course we will still use conditionals to judge whether we should go backwards to a certain label or not.

Wait, I'll share some code when I'm done.

**Comment by BIGjuevos** [comment]
@entrptaher Thanks for the additional info.  So, if I understand correctly, you are trying to emulate the user's behavior within a complex situation?

When we are implementing complicated scenarios like this at work, we split up each path through the software into it's own file instead of grouping them.  Although we cover some things multiple times, we cover all combinations of interactions through that feature or piece of functionality.

**Comment by entrptaher** [comment]
There are tons of features of casperjs. One is very basic function called .echo() .The difference between echo and console.log is, echo can output in color. Why go to such extent just to show some colors?

@BIGjuevos, there are non-important functions as well, while we still can do things using various smaller modules and functions, what the harm in making a simpler way for those who wants it simpler than going through all the trouble?

There was, is and will be someone having a hard time dealing with going back and forth. Otherwise they wouldn't make an issue or create a module at the first place.

**Comment by entrptaher** [comment]
Here... This will go like Step1(main) -> Step2(main)  -> Step1(newtab) ->Step2(main)
the labels in each instance will act separately.

Here the newtab function is copied from someone too. The purpose is to open a new instance while keeping the 1st instance waiting. So we can connect to ExpressJS in the 2nd instance and show something or wait for users manual input.

Now, show me a easier and better way to go back and forth. In this simple program.

```javascript
var MyApp = {}; // Declare a Global scope for using anywhere

var casper = require('casper').create();

// IIFE to hide casper2done variable
(function(casper) {
    var casper2done = false;
    casper.newTab = function(url, then, timeout) {
        if (typeof url !== "string" || typeof then !== "function") {
            throw "URL or then callback are missing";
        }
        this.then(function() {
                var casper2 = require('casper')
                    .create({waitTimeout : timeout});
                casper2.start(url)
                    .then(then)
                    .run(function() {
                        casper2done = true;
                    });
            })
            .waitFor(function check() {
                return casper2done;
            }, null, null, timeout)
            .then(function() {
                casper2done = false;
            });
        return this;
    };
})(casper);

//1st Instance
casper.start("http://indianvisa-bangladesh.nic.in/")
    .label('STEP1')
    .then(function() {
       MyApp.from='nowhere';
       this.echo(MyApp.from);
       this.echo('STEP1 on main');
       this.goto('STEP2');
    })
    .label('NEWTAB')
    .then(function(){
    this.newTab("http://localhost:3000/", function() {
        //2nd Instance
        this.label('STEP1')
        .then(function(){
        this.echo('STEP1 on newtab');
        this.goto('exit')
        })
        
        this.label('STEP2')
        .then(function(){
        this.echo('STEP2 on newtab');
        this.goto('STEP1')
        })
        
        this.label('exit')
        this.then(function(){
          MyApp.from='newtab';
          this.echo(MyApp.from);
          this.exit;
        })
    }, 5000)
    })
    //1st Instance
    .label('STEP2')
    .then(function() {
        this.echo('STEP2 on main');
        if(MyApp.from=='newtab')
        {
          this.goto('END')
          }
        else{
          this.goto('NEWTAB');
        }
        })
    .label('END')
    .run(function() {
        this.echo('Exiting...');
        this.exit();
    });
```

**Comment by entrptaher** [comment]
Here... This will go like Step1(main) -> Step2(main)  -> Step1(newtab) ->Step2(main)
the labels in each instance will act separately.

Here the newtab function is copied from someone too. The purpose is to open a new instance while keeping the 1st instance waiting. So we can connect to ExpressJS in the 2nd instance and show something or wait for users manual input.

Now, show me a easier and better way to go back and forth. In this simple program.

```javascript
var MyApp = {}; // Declare a Global scope for using anywhere

var casper = require('casper').create();

// IIFE to hide casper2done variable
(function(casper) {
    var casper2done = false;
    casper.newTab = function(url, then, timeout) {
        if (typeof url !== "string" || typeof then !== "function") {
            throw "URL or then callback are missing";
        }
        this.then(function() {
                var casper2 = require('casper')
                    .create({waitTimeout : timeout});
                casper2.start(url)
                    .then(then)
                    .run(function() {
                        casper2done = true;
                    });
            })
            .waitFor(function check() {
                return casper2done;
            }, null, null, timeout)
            .then(function() {
                casper2done = false;
            });
        return this;
    };
})(casper);

//1st Instance
casper.start()
    .label('STEP1')
    .then(function() {
       MyApp.from='nowhere';
       this.echo(MyApp.from);
       this.echo('STEP1 on main');
       this.goto('STEP2');
    })
    .label('NEWTAB')
    .then(function(){
    this.newTab("http://localhost:3000/", function() {
        //2nd Instance
        this.label('STEP1')
        .then(function(){
        this.echo('STEP1 on newtab');
        this.goto('exit')
        })
        
        this.label('STEP2')
        .then(function(){
        this.echo('STEP2 on newtab');
        this.goto('STEP1')
        })
        
        this.label('exit')
        this.then(function(){
          MyApp.from='newtab';
          this.echo(MyApp.from);
          this.exit;
        })
    }, 5000)
    })
    //1st Instance
    .label('STEP2')
    .then(function() {
        this.echo('STEP2 on main');
        if(MyApp.from=='newtab')
        {
          this.goto('END')
          }
        else{
          this.goto('NEWTAB');
        }
        })
    .label('END')
    .run(function() {
        this.echo('Exiting...');
        this.exit();
    });
```

**Comment by BIGjuevos** [comment]
@entrptaher I've found a solution using some vanilla CasperJS and some callback structures to represent some primitive locking.  I'm sure with time it could be done in a nicer fashion.  I'm unsure of how well my contrived example scales (it would need to be abstracted a bit).

However, please read below this example as I have more to add on this point.

```javascript
phantom.casperPath = '/path/to/casperjs';
phantom.injectJs(phantom.casperPath + '/bin/bootstrap.js');

// Setup two instances of casper, one for each of our tabs
var casper1 = require('casper').create();
var casper2 = require('casper').create();

var MyApp = {};
var locks = {};

// create a callback system that we can use to execute our async operations synchronously
function lock(name, callback) {
  if ( typeof locks[name] == "undefined" ) {
    locks[name] = [];
    locks[name].push(callback);
  } else {
    locks[name].push(callback);
  }
}

// when we are done with something exeucute the things we queued up
function unlock(name) {
  if ( typeof locks[name] !== "undefined" ) {
    locks[name].forEach( function(cb) {
      cb();
    });
    delete locks[name];
  }
  return false;
}

// This is the first tab
casper1.start()
  .then(function main1() {
    MyApp.from = "nowhere";
    casper1.echo(MyApp.from);
    casper1.echo("STEP 1 on main");
  })
  .then(function main2() {
    lock('main', function() {
      casper1.echo("STEP 2 on main");
    });
      lock('main', function() {
        casper1.echo("casper1 exiting...");
        casper1.exit();
      });
  })
  .then(function manRunTab() {
    casper2.run();
    lock('main', function() {
      casper2.echo("casper2 exiting...");
      casper2.exit();
    });
  })

// This is the second tab
casper2.start()
  .then(function tab1() {
    casper2.echo("STEP 1 on newtab");
  })
  .then(function tab2() {
    casper2.echo("STEP 2 on newtab");
  })
  .then(function tabExit() {
    MyApp.from = "newtab";
    casper2.echo(MyApp.from);

    unlock('main');
  });

casper1.run(function() {
  console.log('casper1 run callback');
});
```

The above outputs the following:
```
:// phantomjs working.js
nowhere
STEP 1 on main
casper1 run callback
STEP 1 on newtab
STEP 2 on newtab
newtab
STEP 2 on main
casper1 exiting...
casper2 exiting...
```

While attempting to solve your problem in a vanilla fashion, I think I came to understand the root of your problem.  It appears you need to manipulate the execution of the queue.  With you much appreciated example in mind, I have an alternative proposal that I think may work just as well, and hopefully be less work.

I propose new queue manipulation methods to allow people to determine in what order the queue should be executed per casper instance.

**casperOptions.autostart**: If set to false, upon calling run(), casper does not go straight to the first thing in the queue.
**casper.stepForward()**: Causes casper to execute the next thing in the queue (just the next thing).  If the end, if the last thing, it acts if it hits end of queue now.
**casper.resumeExecution()**: Causes casper to continue to execute the rest of the queue as if the **autostart** parameter had not been passed in.
**casper.thenBreak()**: A step in the queue that causes the queue to exit pre-maturely and give execution back to the caller to do things.

Let's re-examine the provided example with my proposal.

```javascript
phantom.casperPath = '/Users/rnull/projects/casperjs';
phantom.injectJs(phantom.casperPath + '/bin/bootstrap.js');

// Setup two instances of casper, one for each of our tabs
var casper1 = require('casper').create({
  autostart: false
});
var casper2 = require('casper').create({
  autostart: false
});

var MyApp = {};

// This is the first tab
casper1.start()
  .then(function main1() {
    MyApp.from = "nowhere";
    casper1.echo(MyApp.from);
    casper1.echo("STEP 1 on main");
  })
  .then(function main2() {
    casper1.echo("STEP 2 on main");
  });

// This is the second tab
casper2.start()
  .then(function tab1() {
    casper2.echo("STEP 1 on newtab");
  })
  .then(function tab2() {
    casper2.echo("STEP 2 on newtab");
  })
  .then(function tabExit() {
    MyApp.from = "newtab";
    casper2.echo(MyApp.from);
  });

casper1.run(function() {
  casper1.echo("casper1 exiting...");
  casper1.exit();
});

casper2.run(function() {
  casper2.echo("casper2 exiting...");
  casper2.exit();
});

// run through our events
casper1.stepForward();
casper2.resumeExecution();
casper1.resumeExecution();
```

With this, we aren't adding in additional things to make the series of .then harder to read, and I think that this is easier to follow, things stay sequential, we just control the time at which they are being executed.  Plus, I'm pretty sure we stay completely backwards compatible with a few changes to the internals of the runner.

This scales up realistically by bringing in a larger number of casper instances, and allows implementers to contrive rather convoluted use cases utilizing multiple instances of CasperJS to accomplish multi-page scenarios.

This would further allow for crazy bootstrapping in-between steps of tests and other things that pausing execution of the test queue would bring.

Pinging @istr, @jefleponot  and @mickaelandrieu for their thoughts on my proposal.

**Comment by BIGjuevos** [comment]
@entrptaher, I wanted to point out separately in this thread, that I really do appreciate you taking the time to discuss this.  I know your time is valuable and I appreciate you contributing.

My intentions are to solve your problems as well as to solve the future needs of the community of users.  Problem is, I'm a slow person and take time to catch up with smart and quick guys like you.

So, sincerely.  Thank you for being patient and helping me fully understand your use case.  I plan to not violate the trust you have placed in me and the team by sharing your time with us.

**Comment by entrptaher** [comment]
Your code certainly looks nice.

My purpose of sharing this repo and implementing it was because it solved my problem. And .newtab function has nothing to do with it. It was just a simple sub function to show what I wanted to do using the .goto() function.

If you ask me about the root of the problem, I already mentioned it several times, and it is **jumping between steps at will** without remembering or calculating how many steps there are to bypass..We can just rewrite it and get rid of the usage of .then() after every .label().

Although the enhancement about "manipulating the execution of the queue" is something very interesting.

**Comment by jefleponot** [comment]
Thank you @entrptaher and @BIGjuevos for this great discussion of good tracks.
we agree that casperJS provided too little scheduling functions.

Your proposals improve the execution loop and allow to plan complex tests.

Here is more thinking for you : :memo: 

Since long time, I had to code several of these proposals in my own casperJS fork that was required by complexity of few scenarios:

_1. interactivity, pages and events synchronization, implementation (breakpoint ) ..._

- casperOptions.autostart.
- casper.stepHalt.
- casper.stepForward.
- casper.resumeExecution.

_2. alternative steps execution (depending on webserver response or tests parameters)_

- casper.label.
- casper.goto.
- casper.bypass.

_3. end, tests consolidation, exportation..._ #1422

- casper.stop.
- casper.abort.

Regards

**Comment by jefleponot** [comment]
I talk about interactivity without any sample, :wink: 

command line interactivity :
````javascript
var _system_ = require('system');

function interactiveStep(elm, id){
    this.echo('continue (Default) or Halt (Y) ? ');
    var c = _system_.stdin.read(1);
    if (c.toUpperCase() === 'Y') {
        this.exit(0);
    }
    return this;
};
````

**Comment by istr** [comment]
@BIGjuevos 

> I propose new queue manipulation methods to allow people to determine in what order the queue should be executed per casper instance.

I think that introducing these flow-control methods would have much more benefit than the original (potentially dangerous as you, @jefleponot and me pointed out) idea of introducing a simple ```label```/```goto``` kludge.

**Comment by BIGjuevos** [comment]
I like this for 1.2, any objections?

**Comment by entrptaher** [comment]
@BIGjuevos, so what are the final decision?

**Comment by BIGjuevos** [comment]
*Decision:*

We like your idea, but find it a little dangerous at this point in time.  So, to mitigate this risk, let's go with the following:

1. #1513 Design and implement flow control that CasperJS team settled on (being able to control the queue step by step, and inserting breakpoints).  Rationale:
  - It's predictable to implement.
  - Not too much runner refactoring required.
  - Low defect injection potential.
2. #1514 Design and implement arbitrary step execution (order and sequence) by defining the interface and work on implementing the solution.  Rationale:
  - Will likely require some runner refactoring.
  - Higher risk and likely hood of bug injection.

This phased approach allows us to roll out the functionality with low likely hood of defect injection rate, yet provide the functionality you have developed incrementally.

The two tasks can be found at #1513 and #1514.  Closing this conversation in favor of the newer issues.

Thank you everyone for your contributions!  Open source works because of people like you!
