### ISSUE TITLE
With 1.1.0 release, what is recommended for users?

### ISSUE THREAD

**Issue by avindra** [n1k0/casperjs#1522]
The README states:

> Important note: the master branch hosts the development version of CasperJS, which is now pretty stable and should be the right version to use if you ask me.

> Use the 1.0 branch if you want to keep in sync with the stable old version, or use tagged versions.

Does this still hold true? If not, is 1.1.0 now the recommended release to use? Please clarify.

Thank you.

**Comment by istr** [comment]
See https://github.com/n1k0/casperjs/pull/1521.
I will create a separate PR for the master README update.
