### ISSUE TITLE
fetchText no longer works

### ISSUE THREAD

**Issue by dschinkel** [n1k0/casperjs#1527]
I have a test that was passing just fine and now it doesn't.  There is indeed the text on the page I'm testing for but for some reason my fetchText is no longer working.  I've included both my tests and gulpfile.

**gulpfile.js**

```
"use strict";

var app = require('./server'),
    gulp = require('gulp'),
    shell = require('gulp-shell'),
    wait = require('gulp-wait'),
    watchify = require('watchify'),
    mocha = require('gulp-mocha'),
    runSequence = require('run-sequence'),
    browserify = require('browserify'),
    source = require('vinyl-source-stream'),
    gutil = require('gulp-util'),
    del = require('del'),
    babelify = require('babelify');

var scriptsCount = 0;

var config = {
    port: 3000,
    watch: {
        src: './src/*.js',
    },
    build: {
        bundle: {
            destination: './build/app/js'
        }
    },
    app: {
        path: './src/components/app.js'
    },
    test:{
        root: 'test/**',
        src: {
            unit:'test/unit/**/*-test.js',
            acceptance: 'test/features/specs/*-spec.js'
        },
        mocha: {
            reporter: 'spec'
        }
    }
};

gulp.task('default', function (done){
    runSequence('clean:build','bundleApp','watch','startApp','tests-acceptance', done)
});

gulp.task('clean:build', function () {
    return del(['./build/app/js/*.js'])
});

gulp.task('watch', function () {
    gulp.watch([config.watch.src]);
});

gulp.task('startApp', function () {
    var server = app.listen(config.port, function(){
        console.log('Ready on port %d', server.address().port);
    }).on('error', function(err) {
        console.log(err);
    });
});

gulp.task('bundleApp', function () {
    return bundleApp();
});

function bundleApp() {
    scriptsCount++;

    var appBundler = browserify({
        cache: {},
        packageCache: {},
        plugin: [watchify],
        entries: config.app.path,
        debug: true
    });

    return appBundler
        .transform("babelify", {presets: ["es2015", "react"]})
        .bundle()
        .on('error', gutil.log)
        .pipe(source('bundle.js'))
        .pipe(gulp.dest(config.build.bundle.destination))
}

gulp.task('tests-acceptance', function() {
    process.env.PORT = 8000;
    return gulp.src(config.test.src.acceptance, { read: false })
        .pipe(shell(['mocha-casperjs ' + config.test.src.acceptance]))
});
```

**my-spec.js**

```
"use strict";

var page = null;

describe('Feature: View List of Companies', function() {
    before(function () {
        casper.start('http://localhost:3000');
        page = this;
    });

    it('When I go to the main landing page', function () {
        casper.then(function () {
            expect(page).to.be.a('object');
        });
    });

    describe('Scenario 1: No Companies are Listed', function () {
        it('should see that no companies are listed', function () {
            casper.then(function () {
                expect(this.fetchText('h3')).to.equal('No Companies Found');
            });
        });
    });

    casper.run(function() {
        exitPhantomJS();
    });
});


function exitPhantomJS(){
    this.exit();
}
```

this fails and I can't figure out why ```expect(this.fetchText('h3')).to.equal('No Companies Found');```

<img width="612" alt="screen shot 2016-04-12 at 12 27 12 pm" src="https://cloud.githubusercontent.com/assets/338798/14469603/164987bc-00ab-11e6-86ea-34a2107ad2d0.png">

Again this test was passing fine in the past, so I don't know what changed on either my end or the casperjs end to cause it to just stop passing all of a sudden.

**Comment by BIGjuevos** [comment]
@dschinkel What does your package.json look like?

**Comment by dschinkel** [comment]
ahhhhhh!!!!  the problem is that it's no longer an <h3>.  I rendered a react component so it's really rendered as <h3 data-reactid..>

**Comment by BIGjuevos** [comment]
@dschinkel So, you have it working now?

**Comment by dschinkel** [comment]
Yes.  Just gotta figure out how I'm gonna handle testing react components with this but yea.

**Comment by BIGjuevos** [comment]
If you have any insights to share upon figuring it out, please let us know and we can look at adding your learnings to the docs to help others.

**Comment by dschinkel** [comment]
will do, thanks!

**Comment by istr** [comment]
@dschinkel The best bet is to use a selector that is specific enough to catch your element but not too specific to allow for some variation. Searching for text should be used as a "last-resort" only. Always prefer ```waitForSelector```, ```waitUntilVisible``` and then use the functions that work on selectors to test for content over using ```fetchText```. The latter has its problems and selecting elements by DOM tree is rock-solid. You may use either CSS or XPath selectors.

My rule of thumb here is:
- use long path segments for the selectors, e.g. ```#content .foo .bar .baz h3``` (if you know that your IDs never change, use the closest / innermost ID to start with)
- do not overspecify the classes for the nodes in question, i.e. do not select ```#content.wrapper .foo.center.black .bar.float.whatnot h3.my.fancy.subheading```

**Comment by dschinkel** [comment]
ok thanks a lot istr!  wasn't aware that I was kinda going the wrong route on the casper API

**Comment by dschinkel** [comment]
it's still problematic.  Because react throws in other ids in other types of DOM elements such as <div>.  For example, my test still fails because it can't see the<h3> in this situation because the div it's contained in contains a **data-reactroot ** <div data-reactroot="" id="companyList"><h3>No Companies Found</h3></div>

**Comment by BIGjuevos** [comment]
Would something like waitForSelectorTextChange help?

```javasript
casper.waitForSelectorTextChange('#companyList h3', function() { /** assertions */ });
```

**Comment by istr** [comment]
> So in this case, would it make sense to do something like waitForSelector('h3') right?

No, this is not specific enough. The real ```id``` attributes are the key here. They are unique and probably won't change dynamically. @BIGjuevos pointed out a selector that has a good chance to work.

**Comment by dschinkel** [comment]
you left me with a good point.  I haven't really needed to apply selectors like ids in my code yet.  Maybe once I start to use a little more CSS I might have something better and more specific to work off of but right now I haven't had a need to start using ids, as my app is just starting and is very infant right now...

**Comment by dschinkel** [comment]
so thinking something like this:

```
        it('should see that no companies are listed', function () {
            casper.waitForSelector('#companyList', then(function () {
                expect(.to.equal('No Companies Found');
            });
        });
```

assuming now I'm presenting the id in the div there.  Not sure how to assert it while inside the waitfor though

**Comment by dschinkel** [comment]
Check this out

I still can't move forward with Casper.

Here is my latest test, just testing out the waitForSelector:

    describe('Scenario 1: No Companies are Listed', function () {
        it('should see that no companies are listed', function () {
            casper.waitForSelector('#companyList', function () {});
        });
    });

watch this: https://drive.google.com/file/d/0B6FDE5kMwYTleVFRM1M5dWRDaEk/view?usp=sharing

**Comment by istr** [comment]
Please try to study the examples / documentation and browse for some basic use cases / code snippets. What you're asking for is a primer how to use CasperJS. The github issues are not the right place to ask for.

**Comment by dschinkel** [comment]
You know what would help?  Getting rid of the black background on the Casper site :).

**Comment by dschinkel** [comment]
If you would have watched the video, it's talking about the issue in this thread still, not my example asking about how to select inside the waitForSelector.  Please watch it.

**Comment by istr** [comment]
> You know what would help? Getting rid of the black background on the Casper site :).

Maybe... This is a heritage. But no excuse to avoid reading the docs and/or to search for examples before filing a bug here.

> There's still a problem with Casper reading DOM when react attributes are in DOM elements

No. There is a problem in your application (duplicate ID). Your screencast exposes this. See attached screenshot.

![screenshot](https://cloud.githubusercontent.com/assets/4235579/14495681/bdf5d0fc-0190-11e6-8d55-ff7d79f635ff.png)

It would be nice if you could respect that the github page is meant for contributions to CasperJS, not for helping out actually using it. Thanks for understanding.

**Comment by dschinkel** [comment]
My fault bad example.  There are still problems with casper even when that's not there but whatever...

**Comment by mickaelandrieu** [comment]
> You know what would help? Getting rid of the black background on the Casper site :)

Please, you can download the docs as PDF too, you make me feel down :( https://media.readthedocs.org/pdf/casperjs/1.1.0/casperjs.pdf

**Comment by dschinkel** [comment]
<img width="517" alt="screen shot 2016-04-13 at 9 10 03 am" src="https://cloud.githubusercontent.com/assets/338798/14496065/995bf854-0157-11e6-94c8-1e3beaec60ca.png">
<img width="688" alt="screen shot 2016-04-13 at 9 10 12 am" src="https://cloud.githubusercontent.com/assets/338798/14496067/9b6a3c50-0157-11e6-892e-19c189b3abab.png">

does that make you feel even better :)

**Comment by istr** [comment]
> does that make you feel even better

No. Some reading of netiquette is highly advised. [Please respect other people's time](http://www.albion.com/netiquette/rule4.html). I am locking this conversation now.

**Comment by istr** [comment]
In response to a PM I am unlocking this again.

@dschinkel You pointed out that you think that there "there is still a problem with Casper not being able to read elements with non-native dom attributes in them".

If so, please
- create a minimal working test that isolates this issue only
- check that this is not a problem with the engine (PhantomJS), i.e. verify that your example works when used directly with PhantomJS and without CasperJS
- if it is not a problem with PhantomJS and it turns out to be a real issue with CasperJS, post your minimal working test case that demonstrates the problem in a separate issue with a title that clearly depicts the problem, e.g "Unable to select DOM nodes by ID that contain non-native attributes"
- clearly state the affected CasperJS and PhantomJS version you tested, as well as the platform used to run the failing example on

If you do it like this, everybody else could reproduce / verify your issue very quickly. And your posted failing example is the first step to a test case that will be part of a PR that could fix the problem.

This would help us to improve on CasperJS. Posting random large code snippets / specs / test cases without posting the code it tests, screencasts, and sarcastic comments like "does that make you feel even better" do not help at all. Thanks for your understanding.

**Comment by dschinkel** [comment]
I've opened a new issue, with code.  "check that this is not a problem with the engine (PhantomJS), i.e. verify that your example works when used directly with PhantomJS and without CasperJS".  I'm using node, so unfortunately that's not possible.

**Comment by istr** [comment]
> I'm using node, so unfortunately that's not possible.

It is possible, but some additional work, of course. The point is that we do not accept that you offload this additional work to us by means of filing issues against CasperJS without reflection or without having verified that the problem is with CasperJS and not with your specific test environment and/or application.

Provided that you are willing to do that additional work on your own and provided that you look into and follow some of the examples how this works (start with browsing through closed PRs and issues that provide a minimal, isolated test) I will try to guide you to the process in that other issue. The core of TDD is to be able to track down problems to single, isolated issues, so other people can easily replicate / verify and eventually fix them.

**Comment by dschinkel** [comment]
What pisses me off is this "The point is that we do not accept that you offload this additional work to us by means of filing issues against CasperJS without reflection or without having verified that the problem is with CasperJS and not with your specific test environment and/or application"

I spend 8 hours yesterday on this doing EXACTLY what you inferred I haven't done.  I've been troubleshooting it all fucking day.  Are you saying I haven't?  Do you live with me?  I HAVE done my due dilligence and looked at ton shit of documentation, wtf dude.

**Comment by dschinkel** [comment]
close this thing, fuck it.  Yes I'm not being very community like because your'e kinda being a dick about it.

**Comment by istr** [comment]
@dschinkel I think that the follow-up in #1530 proves you wrong. YMMV. Sorry to see you disappointed, but I can't help it.

**Comment by BIGjuevos** [comment]
Locking this conversation.
