### ISSUE TITLE
Using Evaluate with waitForSelector with Mocha assertions

### ISSUE THREAD

**Issue by dschinkel** [n1k0/casperjs#1529]
I'm able to get my first test to pass but now I'm trying to use jquery  for my second test.

but now I'm trying to get more fancy by using jquery to select the dom element in order to get its value to assert against using chai.js expect and obivously not doing something right here.  I am either not using the right combination of casper functions or not nesting them right (such as should I have evaluate nested inside waitfor?  should I be using thenEvaluate() instead of then()?  Should I have then() inside evaluate()?  It's like there's a lot to figure out when using casper at first.

My html page is rendering this div that I hard coded: 

```<div id="companyList">No Companies Found</div>```

```
"use strict";

var page = null,
    $ = require('jquery');

 before(function () {
        casper.start('http://localhost:3000');
        casper.options.clientScripts = ["../../../public/js/jquery-2.2.3.min.js"];
        casper.on("remote.message", function(msg){
            this.echo("remote.msg: " + msg);
        });
        casper.on("page.error", function(pageErr){
            this.echo("page.err: " + JSON.stringify(pageErr));
        });
        page = this;
    });

    describe('Scenario 1: No Companies are Listed', function () {

        it('When I go to the main landing page', function () {
            casper.then(function () {
                expect(page).to.be.a('object');
            });
        });

        it('should see that no companies are listed', function () {
            casper.waitForSelector('#companyList', function () {
                var companyList = null;
                casper.evaluate(function() {
                    companyList = $('#companyList').value;
                });
                
                casper.then(function(){
                    expect(companyList.to.equal('No Companies Found'));
                })
            });
        });
    });
```

```
  Feature: View List of Companies
page.err: "TypeError: undefined is not a constructor (evaluating 'Object.assign({}, config)')"
    ✓ When I go to the main landing page (40ms)
    Scenario 1: No Companies are Listed
      1) should see that no companies are listed


  1 passing (216ms)
  1 failing

  1) Feature: View List of Companies Scenario 1: No Companies are Listed should see that no companies are listed:
     null is not an object (evaluating 'companyList.to')
```

**Comment by istr** [comment]
> ```companyList = $('#companyList').value;```

?

**Comment by istr** [comment]
Closing for the same reason like #1527. After all, the github issues are not meant to be a help-desk ticketing system. This is not meant to be rude, but we have real issues/bugs to solve. Reviewing issues takes time, too. See https://github.com/n1k0/casperjs/blob/master/README.md / "Support".

**Comment by dschinkel** [comment]
the docs haven't been that helpful in terms of more advanced scenarios TBH.  $ is jquery.
