### ISSUE TITLE
Casper Not Able to Read DOM Elements with Custom React.js attributes

### ISSUE THREAD

**Issue by dschinkel** [n1k0/casperjs#1530]
Why is it that Casper cannot see this id?

<img width="517" alt="screen shot 2016-04-13 at 9 10 03 am" src="https://cloud.githubusercontent.com/assets/338798/14496660/875e5d3e-0159-11e6-85b6-a198c0b04e6b.png">
<img width="688" alt="screen shot 2016-04-13 at 9 10 12 am" src="https://cloud.githubusercontent.com/assets/338798/14496667/887badc0-0159-11e6-9cbc-ebef47e26fd3.png">

React.js is rendering this.  If there are react attributes in DOM elements, Casper can't seem to find anything
```
        it('test', function () {
            casper.waitForSelector('#companyList', function () {
                //can we even get here?  NO!
            });
        });
    });
```

**index.html**
```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- load Ink's CSS -->
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/ink-flex.min.css">
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/font-awesome.min.css">

        <style>
            body {
                background: #ededed;
            }
        </style>
    </head>
    <body>
        <div class="ink-grid vertical-space">
            <!--<div id="companyList">test</div>-->
            <div id="content">
                <div class="panel vertical-space">
                    <div id="app"/>
                </div>
            </div>
        </div>
        <script type="text/javascript" src="build/app/js/bundle.js"></script>
    </body>
</html>
```
Rendered:
<img width="541" alt="screen shot 2016-04-13 at 9 47 16 am" src="https://cloud.githubusercontent.com/assets/338798/14497635/111e7a42-015d-11e6-8da8-fc44740dc725.png">

Fails:
```
 "#companyList" still did not exist 5000ms
```

However, if I hard code it instead of having React.js render it, hence now there's no custom react component attributes (now there's no data-reactid), it works just fine:

**index.html**
```
<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- load Ink's CSS -->
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/ink-flex.min.css">
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/font-awesome.min.css">

        <style>
            body {
                background: #ededed;
            }
        </style>
    </head>
    <body>
        <div class="ink-grid vertical-space">
            <div id="companyList">test</div>
            <div id="content">
                <div class="panel vertical-space">
                    <!--<div id="app"/>-->
                </div>
            </div>
        </div>
        <script type="text/javascript" src="build/app/js/bundle.js"></script>
    </body>
</html>
```

Rendered:

<img width="505" alt="screen shot 2016-04-13 at 9 52 33 am" src="https://cloud.githubusercontent.com/assets/338798/14497760/7f8cc0a6-015d-11e6-8758-bb36b0289aff.png">

Passes:

<img width="569" alt="screen shot 2016-04-13 at 9 54 35 am" src="https://cloud.githubusercontent.com/assets/338798/14497825/cfdca116-015d-11e6-9467-4713aa4a16e3.png">

Why can't Casper work when there are custom attributes?  I'd have to assume people have used Casper with React, Angular, etc. with custom attributes before? If so, why isn't my test passing then in the first scenario?

**Comment by istr** [comment]
Please indicate the CasperJS and PhantomJS versions used as well as the platform you are running the tests on.

Please try to isolate the problem and demonstrate that this is an issue with the custom attribute.

What happens if you hardcode it *including* the custom attribute like in the example below?
Does this pass your test?

If it passes, the problem is not with the custom attribute but probably with the timing of your test (your test runs before react has finished rendering / updating the DOM tree).
If it fails, this could be an issue with either PhantomJS (please verify that it is not) or else with CasperJS.

Please re-check if your "hard-coded" example works or fails with the custom attribute included:
 
**index.html**
```HTML
<html lang="en">
    <head>
        <meta charset="utf-8">

        <!-- load Ink's CSS -->
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/ink-flex.min.css">
        <link rel="stylesheet" type="text/css" href="public/libs/ink-3.1.10/css/font-awesome.min.css">

        <style>
            body {
                background: #ededed;
            }
        </style>
    </head>
    <body>
        <div class="ink-grid vertical-space">
            <div id="companyList" data-react-id=".0">test</div>
            <div id="content">
                <div class="panel vertical-space">
                    <!--<div id="app"/>-->
                </div>
            </div>
        </div>
        <script type="text/javascript" src="build/app/js/bundle.js"></script>
    </body>
</html>
```

**Comment by dschinkel** [comment]
full code, this is in node

https://github.com/dschinkel/we-do-tdd

**Comment by dschinkel** [comment]
well it's able to find it with this hard coded: <div id="companyList" data-react-id=".0">test</div> so maybe it's a timing issue, I'll look into it.

**Comment by dschinkel** [comment]
screw Casper, I'm not using it...if this is how the casper community acts in terms of open source issues.  To claim I haven't done due diligence, well screw you man.

**Comment by istr** [comment]
Sorry that it did not work out. But this project is maintained with very few people aboard in the spare time on a voluntary basis. So we can't provide "full service" for free and need to expect cooperation from the users. I am on my wits' end with ideas how to help you out. Open source is about cooperation and collaboration, not about "getting full service for free".

**Comment by dschinkel** [comment]
Don't patronize me bro.  I never expected what you say "full service".  If you don't have time, don't answer.  But certainly don't insult me by telling me I haven't read docs, or done my due dilligence.

Here is the behavior I see from you how about that?

1) go read the docs
2) you dumped it on us
3) go talk to phantom
4) You're wrong

Fine maybe it is a timing issue, but you were unprofessional in the first place by being passive aggressive with your initial "get out of here go read the docs, you haven't done shit" attitude.

I'm done with this.  Adios.

**Comment by BIGjuevos** [comment]
Locking this conversation.
