### ISSUE TITLE
HTMLElementObject.click()

### ISSUE THREAD

**Issue by linjunpop** [n1k0/casperjs#223]
Script stop execute after call `.click()`

https://gist.github.com/3447051

**Comment by istr** [comment]
https://github.com/ariya/phantomjs/issues/10795.
Seems to be closed with 2.0.0.

**Comment by BIGjuevos** [comment]
@istr This issue is closed on the PhantomJS side.  What docs need to be updated?

**Comment by istr** [comment]
> This issue is closed on the PhantomJS side. What docs need to be updated?

A hint that the lower versions supported by 1.1 have this problem -- to be honest I am currently a bit unsure where to put it best. Feel free to find a good place and put it there. Documentation updates are non-critical so will be merged if basic grammar and spelling looks ok. ;-)

**Comment by BIGjuevos** [comment]
This issue has been added to the docs under a [new section](http://docs.casperjs.org/en/latest/known_issues.html#phantomjs).  Closing issue.
