### ISSUE TITLE
Windows batch script unexpectedly splits arguments and does not support path with spaces

### ISSUE THREAD

**Issue by langholz** [n1k0/casperjs#269]
Summary:
-------------------------
The windows batch script (batchbin\casperjs.bat) breaks the execution of scripts when there are spaces provided in the PATH environment variable or command line arguments are passed with values.

Details:
-------------------------
*Version:*
PhantomJS - Version 1.7
CasperJS - Version 1.0.0-RC4
Windows 8

<dl>
  <dt>Paths with spaces are not supported:</dt>
  <dd>Repro steps:</dd>
  <dd><pre>
> set path=%path%;C:\tmp\Test Folder\phantomjs
> set path=%path%;C:\tmp\Test Folder\casperjs\batchbin
> casperjs dumpargs.js</pre></dd>
  <dd>Output:</dd>
  <dd><pre>Can't open 'C:\tmp\Test'</pre></dd>
  <dt>Invalid splitting of arguments with values:</dt>
  <dd>Repro steps:</dd>
  <dd><pre>
> set path=%path%;C:\tmp\Test Folder\phantomjs
> set path=%path%;C:\tmp\Test Folder\casperjs\batchbin
> casperjs dumpargs.js --test="wo0t" --ph34r</pre></dd>
  <dd>Actual output:</dd>
  <dd><pre>
Casper CLI passed args:
[
    "wo0t"
]
Casper CLI passed options:
{
    "casper-path": "C:\\tmp\\scripts\\casperjs\\batchbin\\..\\",
    "cli": true,
    "test": true,
    "ph34r": true
}</pre></dd>
  <dd>Expected output:</dd>
  <dd><pre>
Casper CLI passed args:
[]
Casper CLI passed options:
{
    "casper-path": "C:\\tmp\\scripts\\casperjs\\batchbin\\..\\",
    "cli": true,
    "test": "wo0t",
    "ph34r": true
}</pre></dd>
</dl>

*dumpargs.js:*
<pre>
var casper = require("casper").create();
casper.echo("Casper CLI passed args:");
require("utils").dump(casper.cli.args);
casper.echo("Casper CLI passed options:");
require("utils").dump(casper.cli.options);
casper.exit();
</pre>

**Comment by Philoozushi** [comment]
For you Windows guys (I'm not one) :
You should try removing `Split(' ')` in `src/casperjs.cs`, line 45, then compile and try Casper again.
