### ISSUE TITLE
Casper#evaluate signature is ambiguous with a single argument that's a single-key object

### ISSUE THREAD

**Issue by nrabinowitz** [n1k0/casperjs#353]
This is the mirror of #349 - if you use the new `casper.evaluate` syntax and want to pass in a single-key object like `{ test: [1,2,3] }`, this will fail:

```js
casper.evaluate(function(test) {
    return JSON.stringify(test);
}, { test: [1,2,3] });
```

Understandably, the code has no way of knowing whether this is an old-syntax invocation or a new-syntax invocation. The workaround is to wrap it in yet another object per the old syntax:

```js
casper.evaluate(function(test) {
    return JSON.stringify(test);
}, { test: { test: [1,2,3] } });
```

But I think this is a bug, because there's no way to make this work using the v1.0.0 syntax.

**Comment by istr** [comment]
@nrabinowitz Could you please check if [the closed companion of this issue](https://github.com/n1k0/casperjs/issues/349) solves this issue as well?

If so, it would be nice if you closed it as "outdated". Thanks a lot.

**Comment by istr** [comment]
No reply for two weeks. Closing as "outdated". Feel free to re-open if this is still relevant for you.
