### ISSUE TITLE
Selftest fails

### ISSUE THREAD

**Issue by p** [n1k0/casperjs#365]
Not sure why yet but this is what I get:

https://gist.github.com/031a0892f3da5422cd9c

FreeBSD reactor.here 9.1-RELEASE FreeBSD 9.1-RELEASE #0 r243825: Tue Dec  4 09:23:10 UTC 2012     root@farrell.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64

phantomjs 1.9.0 (development)

**Comment by istr** [comment]
Test passes with phantomjs 1.9.1 and later. Support for 1.9.0 dropped.
