### ISSUE TITLE
Tester module assumes assertions are issued by the top level file

### ISSUE THREAD

**Issue by p** [n1k0/casperjs#367]
Assuming I am reading the source correctly:

<pre>
        stackEntry = error.stackArray.filter(function(entry) {
            return testFile === entry.sourceURL;
        })[0];
</pre>

If I have a file that requires another file that issues requests and performs assertions, and one of those assertions fails, the entire backtrace is filtered out and the only relevant source information displayed is the top level source file, which is not where the assertion is at all.

**Comment by istr** [comment]
Could you provide a minimal example / test for that (file a that requires file b) as well as what you would expect and the actual outcome of your test?

**Comment by p** [comment]
I do not have those unfortunately.

The top level test would be e.g. one of these: https://github.com/p/wolis-phpbb/tree/master/tests and the non-top level code would be e.g. here: https://github.com/p/wolis-phpbb/blob/master/frontend/utils.coffee

I have not used casperjs since 2013 thus coming up with a reduced test case is rather difficult.

**Comment by istr** [comment]
Ok. Closing "not reproducible" / "outdated". Feel free to re-open when appropriate.
