### ISSUE TITLE
What about add a parameter index to click and other functions?

### ISSUE THREAD

**Issue by RockLi** [n1k0/casperjs#437]
click and other events implemented  in CasperJs are using ```document.querySelector``` to get one element, but sometimes It's impossible to query one element by using CSS3 selector.

So I wonder if you are planning to add a new parameter or function to let callers can obviously passing the **index**. I have added this functionality to my local casperjs clone. 

If you and others think this make sense, I will send the PR.

**Comment by istr** [comment]
There is [broad support for CSS3 selectors now](http://caniuse.com/#feat=css-sel3), so current versions of Phantom should support that, including [:nth-last-child](https://developer.mozilla.org/en-US/docs/Web/CSS/%3Anth-last-child).

Please try that.
