### ISSUE TITLE
Allow 'selftest' to make 4xx and 5xx tests in "HTTP status code handling" for PhantomJS 1.10.0

### ISSUE THREAD

**Issue by oloynet** [n1k0/casperjs#444]
Hello,

Since the closed issue https://github.com/ariya/phantomjs/issues/11163 in PhantomJS, 
is it possible to allow 4xx and 5xx tests in file
https://github.com/n1k0/casperjs/blob/master/tests/suites/http_status.js

I've successfully tested PhantomJS 1.10.0 (development) with CasperJS
Now there are 844 functional tests instead of 742

    PASS 844 tests executed in 20.715s, 844 passed, 0 failed, 0 dubious, 5 skipped. 

Olivier

**Comment by istr** [comment]
I don't think that "```1.10.0```" is going to happen. The according tests are in place for all engine types and versions that are known to support this (see ```tests/suites/http_status.js``` in current master).
