### ISSUE TITLE
npmjs.org package?

### ISSUE THREAD

**Issue by kanzure** [n1k0/casperjs#462]
Could someone from casperjs upstream please publish casperjs to a public npm registry?

There's already a `package.json` present in the current repository, so it should be ready to go (although make sure to add `"engines": {"phantomjs":"*"}` or whatever). You just need to type a quick `npm publish` whenever you bump the version in `package.json` or add this to a git hook somewhere etc..

Alternatively, if there's already a package up in a npm registry somewhere, then it would be great if the README could mention this more prominently.

I use npm to manage phantomjs modules, and it would be nice to have an official casperjs package that I could add as a dependency when I might want to use casperjs in a public project.

Finally, if casperjs maintainers would rather that I publish casperjs to that npm registry, I would be happy to do that.

**Comment by istr** [comment]
[CasperJS 1.1.0-beta3 is available through www.npmjs.com](https://www.npmjs.com/package/casperjs) for quite a while now and already has quite a number of Dependents.
