### ISSUE TITLE
Opening urls with hash tags (#) have an unstable behaviour 

### ISSUE THREAD

**Issue by yamsellem** [n1k0/casperjs#468]
The following code is unstable:

```javascript
casper.start urlHome +'/#user', -> ...
```

Requirejs 2.0 fails to load some files with a timeout in some cases, but succeed in others.
Maybe the page's ressources (js, css, images) are loaded relatively to `url/#user/` instead of `url/`. Maybe it comes from Phantom.

Still, it's odd.

**Comment by istr** [comment]
Added a [test case for this issue](https://github.com/n1k0/casperjs/pull/1369). Closing, because [automated tests pass](https://travis-ci.org/n1k0/casperjs/builds/94869840).

**Comment by casas111** [comment]
Hello I'm having this situation. My problem is that if the fragment is not added in the load function, then the web page redirects to another page. This makes @el3ment solution useless for me. 

I'm working with casperjs version 1.1.3 and phantomjs version 2.1.1 please help

**Comment by jefleponot** [comment]
Hi @casas111 
Thank you for refresh this old issue.

I will have a look at this trouble
