### ISSUE TITLE
Potential Issue with ClientUtils.visible()

### ISSUE THREAD

**Issue by mhupman** [n1k0/casperjs#498]
I haven't been able to track down the exact scenario that causes this issue to happen, but I thought I'd post it here in case others were experiencing it as well.

Basically, I'm getting runtime exceptions when calling ```ClientUtils.visible``` (nested call from ```casper.waitUntilVisible('#lightbox');```) on line https://github.com/n1k0/casperjs/blob/master/modules/clientutils.js#L852.  The exception is as follows:

```
[BROWSER] Error: TypeError: 'undefined' is not a function (evaluating 'this.each(function(value, index) {
if (result = !!iterator.call(context, value, index))
     throw $break;
})')
[BROWSER] Stack Trace: 
[BROWSER]     https://example.com/js:any (889)
[BROWSER]     /Users/mhupman/repo/appler/casperjs/modules/clientutils.js:visible (852)
[BROWSER]     phantomjs://webpage.evaluate():_evaluate (2)
[BROWSER]     phantomjs://webpage.evaluate():[anonymous] (3)
[BROWSER]     phantomjs://webpage.evaluate():[anonymous] (3)
```

This started happening recently on my systems, but unfortunately, I can't seem to narrow it down to any particular source:

* I tried multiple phantomjs versions, ```1.8.1``` and ```1.9.0```, but both errored.
* I looked over the PR that @hexid made (https://github.com/n1k0/casperjs/pull/469) since it significantly changed ```ClientUtils.visible()```, but can't find any particular issue with it.
* Most telling, however, is that all the ```ClientUtils.visible()``` tests are still passing, both locally and on travis, so I'm not sure if it's a side-affect of the way I'm using it.

For my particular use case, however, the issue seemed to be that attempting to call Array functions on the NodeList object was causing this exception to be thrown.  If the NodeList was first converted to an Array, then everything proceeded as expected.  See https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Why_can't_I_use_forEach_or_map_on_a_NodeList.3F

Anyway, I was able to fix it in my case by applying the following patch that attempts to convert the NodeList into an Array.  I'd be happy to clean it up and submit tests if the root cause (if any) can be determined. https://github.com/mhupman/casperjs/commit/57391d83fc3e0ab2e477f43a0b7d828068b1e7b9

**Comment by istr** [comment]
@mhupman Like the [MDN entry you referenced points out](https://developer.mozilla.org/en-US/docs/Web/API/NodeList#Why_can't_I_use_forEach_or_map_on_a_NodeList.3F) in fact *"```NodeList``` objects don't have any of the familiar ```Array``` methods."*

I know that @n1k0 has a strong preference for the generics ```Array``` provides over "traditional" loops, and probably this is why ```modules/clientutils.js``` converts the ```NodeList``` to an array within ```findAll```in current master (L. 339). ```visible``` simply iterates over the output of ```findAll```.

I doubt that this issue persists in current master; feel free to re-open if you are able to replicate this problem with current master.
