### ISSUE TITLE
Document use & configuration of ANSICON with casperjs

### ISSUE THREAD

**Issue by n1k0** [n1k0/casperjs#504]
https://github.com/adoxa/ansicon

**Comment by paazmaya** [comment]
@n1k0 any pointers how to go forward with this?
Haven't ever used ansicon...

**Comment by n1k0** [comment]
@paazmaya me neither tbh… I don't use Windows, nor want to install it. I've always delegated Windows support to contributors, so that's probably a task for them :)

**Comment by paazmaya** [comment]
Just wanted to ping this since it is marked for `1.1` which I would like to see going out soon...

**Comment by istr** [comment]
This is in place since 1.1.0-beta1, see #490. We might have an issue with slimerjs there, but that's another story.
