### ISSUE TITLE
Document SlimerJS support

### ISSUE THREAD

**Issue by n1k0** [n1k0/casperjs#532]
[CasperJS 1.1 documentation](http://docs.casperjs.org/en/latest/) should be updated to  highlight the support it brings for [SlimerJS](http://slimerjs.org/), now #483 has been merged and #482 closed:

- <del>update `README` (@n1k0)</del>
- <del>highlight support on the docs homepage (@n1k0)</del>
- <del>quick slimerjs installation instructions (@laurentj)</del>
- <del>document the new `--engine` option (@laurentj)</del>
- possibly add a new dedicated section highlighting the differences with phantomjs in terms of usage (@laurentj)
- <del>archive old site for 1.0 (maybe just keep the homepage) (@n1k0)</del>

**Comment by paazmaya** [comment]
Is the "possibly add a new dedicated section highlighting the differences with phantomjs in terms of usage (@laurentj)" part considered to be done in wiki or somewhere else?

**Comment by mickaelandrieu** [comment]
@istr could be easily closed by adding links suggested by @laurentj 

> For the last point to document, is a link to http://docs.slimerjs.org/current/differences-with-phantomjs.html enough? and/or http://slimerjs.org/features ?

I can make a pull request for it, then we can push a new release (publish a new release will close https://github.com/n1k0/casperjs/issues/1260 "de facto" )

**Comment by istr** [comment]
@mickaelandrieu Ok, great. Let's do it!
