### ISSUE TITLE
Can not find module issue

### ISSUE THREAD

**Issue by jingzheshan** [n1k0/casperjs#533]
Hi,

I was using phantomjs 1.9.1 and casperjs 1.0.3, all the tests are running perfect without any problem.

After upgradation to casperjs 1.1
It gave me: 

```
Error: Cannot find module '.\Web\Web\Areas\Testing\Scripts\casperjs\modules\cli.js'

  phantomjs://bootstrap.js:289
  phantomjs://bootstrap.js:254 in require
  .\Web\Web\Areas\Testing\Scripts\casperjs\bin\bootstrap.js:205 in patchedRequire
  .\Web\Web\Areas\Testing\Scripts\casperjs\bin\bootstrap.js:322
  .\Web\Web\Areas\Testing\Scripts\casperjs\bin\bootstrap.js:342
```

Thanks

**Comment by istr** [comment]
Closing. Not enough information to reproduce and seems outdated.

Feel free to re-open if you can provide a script that helps us reproduce your issue if it is still relevant.
