### ISSUE TITLE
__file__ is not found inside modules

### ISSUE THREAD

**Issue by indirect** [n1k0/casperjs#552]
When trying to access the `__file__` variable mentioned in [the debugging documentation](http://docs.casperjs.org/en/latest/debugging.html#localize-yourself-in-modules), casper raises an error:

```
$ casperjs --version
1.1.0-DEV

$ cat test.js
var other = require("other.js");
console.log(other.filename);

$ cat other.js
module.exports.file = __file__;

$ casperjs test.js
ReferenceError: Can't find variable: __file__

  /Users/andre/casperjs/testcase/other.js:1
  /Users/andre/casperjs/testcase/other.js:2
undefined
```

**Comment by istr** [comment]
Updated documentation [is online](http://docs.casperjs.org/en/latest/debugging.html#localize-yourself-in-modules). Closing.

Feel free to re-open if you still think that it is a good idea to re-introduce ```__file__```.
