### ISSUE TITLE
batchbin/casperjs.bat escapes closing quote on --casper-path arg.

### ISSUE THREAD

**Issue by QWp6t** [n1k0/casperjs#562]
If a trailing backslash is used in `%CASPER_PATH%`, it will escape the closing quote in command-line option `--casper-path`.

CasperJS v1.1.0-DEV
PhantomJS v1.9.1
Windows Windows 8 (v6.2 / b9200) x86-64

**Comment by istr** [comment]
Outdated. ```batchbin/casperjs.bat``` [was dropped](https://github.com/n1k0/casperjs/commit/a5a2cd52107bafb4de6106384747e0ed0c1aa34e).
