### ISSUE TITLE
--proxy param not working for casperjs but runs fine in phantomjs

### ISSUE THREAD

**Issue by rgauny** [n1k0/casperjs#584]
Phantomjs version 1.9
Casperjs version 1.1.0-DEV
OS: Windows 7 Ultimate (when checking the same test on Ubuntu everything worked as expected)

The below script runs fine when using phantomjs `--proxy`, when i just change the command to casperjs the script runs but the request doesnt actually go through the proxy and my ipaddress is returned in the screenshot instead of the proxy.

```js
var page = require('webpage').create();
page.open('http://checker.samair.ru/', function () {
    page.render("./screenShot/proxycheck.png")
    phantom.exit();
});
```

**Comment by istr** [comment]
Outdated. ```batchbin/casperjs.bat``` [was dropped](https://github.com/n1k0/casperjs/commit/a5a2cd52107bafb4de6106384747e0ed0c1aa34e).

Feel free to re-open if you still encounter this issue with current master.
