### ISSUE TITLE
Add support for setting the width/height for the generated image via capture()

### ISSUE THREAD

**Issue by dotnetCarpenter** [n1k0/casperjs#586]
I'm trying to set the generated image size, when creating screen dumps with `casperjs`.
I initially thought that [capture()](docs.casperjs.org/en/latest/modules/casper.html#capture) could do what I wanted, through the ´clipRect` object but after creating a test case, I  see that I misunderstood the function.

Since the [zoom()](http://docs.casperjs.org/en/latest/modules/casper.html#zoom) function doesn't accept negative values, I think we're missing key functionality.

Right now I'm on Windows and was unable to run `make test` even with [Make for Windows](http://gnuwin32.sourceforge.net/packages/make.htm) installed. I guess I'm missing python. Would be nice with a cross platform test solution.

I'm running `casperjs` from the master branch.

**Comment by istr** [comment]
Seems to be outdated / invalid to me. CasperJS supports this and other tools like [PhantomCSS](https://github.com/Huddle/PhantomCSS) heavily rely on this feature.

Feel free to re-open if you could elaborate on the specific use-case (test script example, underlying engine with version, and CasperJS version) where this fails for you.

**Comment by dotnetCarpenter** [comment]
I'm pretty sure you're right :8ball:
