### ISSUE TITLE
unable to click links (or load) in dynamic iframe

### ISSUE THREAD

**Issue by eph214** [n1k0/casperjs#603]
Hi, I'm attempting to click links in dynamic iframe.

here's an example:

I'm trying to click dynamic links in a dynamic iframe (which fails):

```js
var casper = require('casper').create();

casper.start('http://dreamcreditcard.net');
casper.wait(5000);

casper.withFrame('master-1', function() {
    this.echo('Page url is ' + this.getCurrentUrl());
    this.echo(this.page.content);
    this.click('a');
});

casper.run();
```

**Comment by istr** [comment]
This discussion belongs to [the mailing list](https://groups.google.com/forum/#!forum/casperjs).

Closing, because @dharrya presented a seemingly valid solution.
