### ISSUE TITLE
Implement `resource.error`

### ISSUE THREAD

**Issue by dpashkevich** [n1k0/casperjs#610]
Currently CasperJS implements `resource.received` and `resource.requested` but it would be great to also have `resource.error` event to get notified of any failed external resource requests (PhantomJS has [`onResourceError`](https://github.com/ariya/phantomjs/wiki/API-Reference-WebPage#wiki-webpage-onResourceError) event for that)

**Comment by istr** [comment]
Implemented [in this commit](https://github.com/n1k0/casperjs/commit/8a75d22ea99dfbe63d523db0cae0232078044b55).
