### ISSUE TITLE
Wrong traceback

### ISSUE THREAD

**Issue by ebrehault** [n1k0/casperjs#668]
With 1.1-beta2, when a test fails, the traceback complains about the usage of begin():
"looks like you did not use begin(), which is mandatory since 1.1"
despite we do use begin().
And it also contains a long long error value.

here is an example (based on an example copied in the casperjs documentation):
https://gist.github.com/ebrehault/6925103

Note: with 1.1-beta1, the behaviour is correct.

**Comment by istr** [comment]
Works for me with current master and phantomjs 1.9.6, 2.0.0, 2.0.1 private pre-relase, and slimerjs 0.9.5.

Please re-open if a re-check on your side using current master and phantomjs 1.9.1 through 1.9.5 fails.
