### ISSUE TITLE
Tags don't match version

### ISSUE THREAD

**Issue by nirvdrum** [n1k0/casperjs#742]
I'm working on adding CasperJS installation to a system provisioning tool and ran into a hurdle around versions.  While the version is tagged as '1.1-beta3' (and thus what the download artifact uses), `casperjs --version` reports back '1.1.0-beta3'.  I think the third part is probably significant, so the tags should probably be '1.1.0-betaX'.  I'm not expecting you to retag anything, but maybe if there's a beta4 release they can be made match.

**Comment by istr** [comment]
Closing in favor of related issue https://github.com/n1k0/casperjs/issues/1260.
