### ISSUE TITLE
Travis build: the python exec version doesn't run jshint

### ISSUE THREAD

**Issue by n1k0** [n1k0/casperjs#768]
https://travis-ci.org/n1k0/casperjs/builds/15502453
https://travis-ci.org/n1k0/casperjs/jobs/15502454 should fail with the same jshint errors as with the .net version

**Comment by istr** [comment]
Outdated and fixed imho:

Makefile
- uses ```eslint``` now
- has got a separate ```lint``` target now
- ```test``` target depends on ```lint``` target
