### ISSUE TITLE
Travis-CI always running PhantomJS v1.9.2

### ISSUE THREAD

**Issue by hexid** [n1k0/casperjs#775]
This is just a theory, because Travis-CI comes with `phantomjs` on the path [[source]](http://about.travis-ci.org/docs/user/ci-environment/#Headless-Browser-Testing-Tools).

I'm preparing a PR that will call `casperjs --help` in the Travis build, since that command also prints out the current engine and engine version.

If I'm correct, the fix would be to add checking `ENGINE_EXECUTABLE` to the Python and dotNET launchers.

**Comment by istr** [comment]
Closed with [PR 1310](https://github.com/n1k0/casperjs/pull/1310).
