### ISSUE TITLE
selftest fails for FreeBSD

### ISSUE THREAD

**Issue by gosom** [n1k0/casperjs#806]
$uname -a:
    FreeBSD cr81 9.2-STABLE FreeBSD 9.2-STABLE #0 

    phantomjs --version                                                            
    1.9.2                                        

    casperjs --version                                                              
    1.1.0-beta3                                             

   casperjs selftest 
    
    FAIL 985 tests executed in 30.636s, 982 passed, 3 failed, 0 dubious, 5 skipped.                                       
    Details for the 3 failed tests:       
                                                                                
    In /root/casperjs/tests/suites/casper/formfill.js:134                                                                 
    multiple forms                                                                                                      
    assertUrlMatch: Casper.fill() handles multiple forms                                                              
    In /root/casperjs/tests/suites/casper/formfill.js:157                                                                 
    field array  
    assertUrlMatch: Casper.fill() handles array syntax field names                                                    
    In /root/casperjs/tests/suites/casper/navigation.js:38                                                                
    Form Submittal updates the response                                                                                 
    assertUrlMatch: URL matches form action

**Comment by istr** [comment]
Please re-check against current master and re-open if you still encounter the issue.
