### ISSUE TITLE
content-edit when reset:true is not clearing the content

### ISSUE THREAD

**Issue by gopikrishnaA** [n1k0/casperjs#809]
(Boolean) reset:
When set to true, this option will first empty the current field value. By default, it’s set to false and sendKeys() will just append string to the current field value.
I am using following command for content-editable='true' edit box

this.sendKeys('form#event-form div.nicEdit-main', 'gopi', {reset: true ,keepFocus: true});

The issue was it is not clearing the current field value.But it is appending the current field value.Please tell me how to clear the current content.

**Comment by istr** [comment]
Please address your question to [the mailing list](https://groups.google.com/forum/#!forum/casperjs) if it is still relevant for you. Probably this is an engine-related issue with sendkeys (other projects point to similar problems for webkit based engines).
