### ISSUE TITLE
selftest hangs on flow.coffee

### ISSUE THREAD

**Issue by wefarrell** [n1k0/casperjs#816]
fails when I try to run coffeescript files
running Ubuntu 13.10 and coffeescript 1.7.1

**Comment by Gyomu** [comment]
Are you using phantomjs 2 ? If so, please see commmit b592a6434dcef24633b40c7688c667b8ea466cc7 concerning PR to n1k0#1137

**Comment by istr** [comment]
@wefarrell, @Yurko-Fedoriv please include the engine type and version you are using (e.g. ```phantomjs -v``` or ```slimerjs -v```) to clarify this issue. Thanks.

**Comment by istr** [comment]
Closing due to insufficient information to be able to reproduce.
