### ISSUE TITLE
Emulating touch events

### ISSUE THREAD

**Issue by jplahn** [n1k0/casperjs#946]
Is there any straightforward way to emulate a touch/tap event with Casper? I'm currently testing a web-app to be deployed to an iPad and it only responds to touch events. AFAIK, Casper does not have any built in touch events and I don't believe does Phantom does either, though I may be wrong there.

I approached it from a jQuery perspective, but that didn't yield any success. Not sure if there's a viable way through Casper to emulate a touch and if not, if there's any thought on including that down the line for situations like this, which I'm sure will become more common?

**Comment by zezhou** [comment]
I post a pr  here to support this.touch method by emulating touch events. https://github.com/n1k0/casperjs/pull/1018#issuecomment-56479604

wish it helps.

**Comment by istr** [comment]
Duplicate of https://github.com/n1k0/casperjs/issues/430.
